"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ScrollText } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Audit = { id: string; action: string; entityType: string; entityId?: string; summary: string; metadata?: unknown; createdAt: string; actor?: { firstName: string; lastName: string; email: string } };
const filters = ["", "CLIENT", "PROJECT", "TASK", "INVOICE", "WALLET"];
export default function AuditPage() {
  const [logs, setLogs] = useState<Audit[]>([]); const [filter, setFilter] = useState("");
  const load = useCallback(async (value = "") => { const response = await authFetch(`/audit-logs${value ? `?entityType=${value}` : ""}`); if (response.ok) setLogs(await response.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-5xl"><Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link><div className="mb-7"><p className="text-sm font-semibold text-[#176b5b]">SECURITY & CONTROL</p><h1 className="mt-1 text-3xl font-bold">Audit log</h1><p className="mt-2 text-sm text-[#6d7975]">A permanent timeline of important administrative and financial activity.</p></div><section className="card overflow-hidden"><div className="flex flex-wrap items-center gap-2 border-b border-[#e5eae7] p-5"><ScrollText size={18} className="text-[#176b5b]"/><span className="font-bold">Activity</span><select value={filter} onChange={(event) => { setFilter(event.target.value); void load(event.target.value); }} className="ml-auto rounded-lg border border-[#dbe2df] bg-white px-3 py-2 text-xs font-bold">{filters.map((value) => <option key={value} value={value}>{value || "ALL TYPES"}</option>)}</select></div><div className="divide-y divide-[#e7ebe9]">{logs.map((log) => <div key={log.id} className="flex gap-4 p-5"><div className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-[#176b5b]"/><div className="min-w-0 flex-1"><div className="font-semibold">{log.summary}</div><div className="mt-1 text-xs text-[#77837e]">{log.actor ? `${log.actor.firstName} ${log.actor.lastName}` : "System"} · {new Date(log.createdAt).toLocaleString()}</div></div><div className="text-right"><span className="rounded-full bg-[#edf4f1] px-2 py-1 text-[10px] font-bold text-[#176b5b]">{log.entityType}</span><div className="mt-2 text-[10px] font-bold text-[#89938f]">{log.action}</div></div></div>)}{!logs.length && <div className="p-10 text-center text-sm text-[#7b8782]">No recorded activity yet.</div>}</div></section></div></main>;
}
