"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ChevronLeft, ChevronRight, Circle, ListTodo } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type User = { id: string; firstName: string; lastName: string };
type CalendarTask = { id: string; title: string; status: string; priority: string; dueDate: string; timing: "OVERDUE" | "UPCOMING" | "COMPLETED"; project?: { code: string; name: string; client?: { id: string; name: string } }; assignments: { user: User }[] };
const weekdayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export default function CalendarPage() {
  const [month, setMonth] = useState(new Date(2000, 0, 1)); const [ready, setReady] = useState(false);
  const [tasks, setTasks] = useState<CalendarTask[]>([]); const [users, setUsers] = useState<User[]>([]); const [selectedUser, setSelectedUser] = useState(""); const [isAdmin, setIsAdmin] = useState(false);
  const load = useCallback(async (activeMonth: Date, userId = "") => { const from = new Date(activeMonth.getFullYear(), activeMonth.getMonth(), 1); const to = new Date(activeMonth.getFullYear(), activeMonth.getMonth() + 1, 0, 23, 59, 59); const response = await authFetch(`/calendar?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}${userId ? `&userId=${userId}` : ""}`); if (response.ok) setTasks(await response.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); const admin = session.user.roles.includes("ADMIN"); const timer = window.setTimeout(() => { const now = new Date(); const current = new Date(now.getFullYear(), now.getMonth(), 1); setMonth(current); setIsAdmin(admin); setReady(true); void load(current); if (admin) void authFetch("/users/assignable").then(async (response) => response.ok && setUsers(await response.json())); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const days = useMemo(() => { const firstDay = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); return Array.from({ length: 42 }, (_, index) => { const date = new Date(month.getFullYear(), month.getMonth(), index - firstDay + 1); return { date, current: date.getMonth() === month.getMonth() }; }); }, [month]);
  function changeMonth(offset: number) { const next = new Date(month.getFullYear(), month.getMonth() + offset, 1); setMonth(next); void load(next, selectedUser); }
  function selectUser(id: string) { setSelectedUser(id); void load(month, id); }
  const back = isAdmin ? "/admin" : "/employee";
  return <main className="min-h-screen bg-[#f3f6f4] p-4 md:p-8"><div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-wrap items-center gap-3"><Link href={back} className="flex items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Back to dashboard</Link><Link href="/todo" className="ml-auto flex items-center gap-2 rounded-lg border border-[#d9e1dd] bg-white px-3 py-2 text-sm font-semibold"><ListTodo size={16}/> Personal to-do</Link></div>
    <section className="card overflow-hidden"><header className="flex flex-col gap-4 border-b border-[#e5eae7] p-5 sm:flex-row sm:items-center"><div><p className="text-xs font-bold tracking-wider text-[#176b5b]">TASK CALENDAR</p><h1 className="mt-1 text-2xl font-bold">{ready ? month.toLocaleDateString(undefined, { month: "long", year: "numeric" }) : "Calendar"}</h1></div><div className="flex items-center gap-2 sm:ml-auto">{isAdmin && <select value={selectedUser} onChange={(event) => selectUser(event.target.value)} className="rounded-lg border border-[#d9e1dd] bg-white px-3 py-2 text-sm"><option value="">All employees</option>{users.map((user) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select>}<button onClick={() => changeMonth(-1)} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9e1dd]"><ChevronLeft size={18}/></button><button onClick={() => { const now = new Date(); const current = new Date(now.getFullYear(), now.getMonth(), 1); setMonth(current); void load(current, selectedUser); }} className="rounded-lg border border-[#d9e1dd] px-3 py-2 text-xs font-bold">Today</button><button onClick={() => changeMonth(1)} className="grid h-9 w-9 place-items-center rounded-lg border border-[#d9e1dd]"><ChevronRight size={18}/></button></div></header>
      <div className="grid grid-cols-7 border-b border-[#e5eae7] bg-[#f8faf9]">{weekdayNames.map((day) => <div key={day} className="p-2 text-center text-[10px] font-bold tracking-wider text-[#75817c] md:p-3">{day}</div>)}</div>
      <div className="grid grid-cols-7">{days.map(({ date, current }, index) => { const dateTasks = tasks.filter((task) => new Date(task.dueDate).toDateString() === date.toDateString()); const today = date.toDateString() === new Date().toDateString(); return <div key={index} className={`min-h-24 border-b border-r border-[#e7ebe9] p-1.5 md:min-h-32 md:p-2 ${current ? "bg-white" : "bg-[#fafbfa]"}`}><div className={`mb-1 grid h-6 w-6 place-items-center rounded-full text-xs ${today ? "bg-[#176b5b] font-bold text-white" : current ? "text-[#34413c]" : "text-[#b2bbb7]"}`}>{date.getDate()}</div><div className="space-y-1">{dateTasks.slice(0, 3).map((task) => <div title={`${task.title} — ${task.project ? `${task.project.code} · ${task.project.name}` : "No project"}${task.project?.client ? ` · Client: ${task.project.client.name}` : ""} — ${task.assignments.map(({ user }) => user.firstName).join(", ")}`} key={task.id} className={`truncate rounded px-1.5 py-1 text-[9px] font-semibold md:text-[10px] ${task.timing === "OVERDUE" ? "bg-red-50 text-red-700" : task.timing === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : "bg-blue-50 text-blue-700"}`}><Circle size={6} className="mr-1 inline fill-current"/>{task.title}<span className="hidden md:inline"> · {task.project?.name ?? "No project"}</span></div>)}{dateTasks.length > 3 && <div className="text-[9px] text-[#78847f]">+{dateTasks.length - 3} more</div>}</div></div>; })}</div>
      <footer className="flex flex-wrap gap-4 p-4 text-xs text-[#65716d]"><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-red-500"/>Overdue</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-blue-500"/>Upcoming</span><span className="flex items-center gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-emerald-500"/>Completed</span></footer>
    </section>
  </div></main>;
}
