import { BadRequestException, Body, Controller, Get, Inject, Module, Param, Patch, Post, Req, UseGuards } from "@nestjs/common";
import { ApiBearerAuth, ApiTags } from "@nestjs/swagger";
import { IsIn, IsISO8601, IsInt, IsNumber, IsOptional, IsString, Min, MinLength } from "class-validator";
import { JwtAuthGuard } from "../../auth/jwt-auth.guard.js";
import { Roles, RolesGuard } from "../../auth/roles.guard.js";
import type { AuthRequest } from "../../auth/auth.types.js";
import { PrismaService } from "../../database/prisma.service.js";

const assetStatuses = ["ACTIVE", "IN_SERVICE", "UNDER_REPAIR", "RETIRED"] as const;
const expenseTypes = ["SERVICE", "REPAIR", "UPGRADE"] as const;
class CreateAssetDto { @IsString() @MinLength(2) name!: string; @IsOptional() @IsString() category?: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsString() serialNumber?: string; @IsISO8601() purchaseDate!: string; @IsNumber() @Min(0) purchaseCost!: number; @IsOptional() @IsString() financialAccountId?: string; @IsOptional() @IsNumber() @Min(0) salvageValue?: number; @IsOptional() @IsInt() @Min(1) usefulLifeMonths?: number; @IsOptional() @IsString() assignedToId?: string; }
class UpdateAssetDto { @IsOptional() @IsString() name?: string; @IsOptional() @IsString() category?: string; @IsOptional() @IsString() description?: string; @IsOptional() @IsString() serialNumber?: string; @IsOptional() @IsNumber() @Min(0) salvageValue?: number; @IsOptional() @IsInt() @Min(1) usefulLifeMonths?: number; @IsOptional() @IsString() assignedToId?: string; @IsOptional() @IsIn(assetStatuses) status?: typeof assetStatuses[number]; }
class AssetExpenseDto { @IsIn(expenseTypes) type!: typeof expenseTypes[number]; @IsNumber() @Min(0.01) amount!: number; @IsString() financialAccountId!: string; @IsISO8601() eventDate!: string; @IsString() @MinLength(2) description!: string; @IsOptional() @IsString() reference?: string; }
class SellAssetDto { @IsNumber() @Min(0.01) amount!: number; @IsString() financialAccountId!: string; @IsISO8601() soldAt!: string; @IsOptional() @IsString() reference?: string; @IsOptional() @IsString() note?: string; }

@ApiTags("assets") @ApiBearerAuth() @UseGuards(JwtAuthGuard, RolesGuard) @Roles("ADMIN") @Controller("assets")
class AssetsController {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService) {}
  private values<T extends { purchaseCost: unknown; salvageValue: unknown; usefulLifeMonths: number | null; depreciationStartDate: Date | null; purchaseDate: Date; soldAt: Date | null; events: { type: string; amount: unknown }[] }>(asset: T) { const cost = Number(asset.purchaseCost), salvage = Math.min(cost, Number(asset.salvageValue)), end = asset.soldAt ?? new Date(), start = asset.depreciationStartDate ?? asset.purchaseDate; const days = Math.max(0, (end.getTime() - start.getTime()) / 86400000), lifeDays = asset.usefulLifeMonths ? asset.usefulLifeMonths * 365.25 / 12 : 0, depreciation = lifeDays ? Math.min(cost - salvage, (cost - salvage) * days / lifeDays) : 0; const serviceCost = asset.events.filter((event) => ["SERVICE", "REPAIR", "UPGRADE"].includes(event.type)).reduce((sum, event) => sum + Number(event.amount), 0); return { ...asset, currentBookValue: Math.max(salvage, cost - depreciation), accumulatedDepreciation: depreciation, dailyDepreciation: lifeDays ? (cost - salvage) / lifeDays : 0, serviceCost }; }
  @Get() async list(@Req() request: AuthRequest) { const assets = await this.prisma.asset.findMany({ where: { organizationId: request.user.organizationId }, include: { assignedTo: { select: { id: true, firstName: true, lastName: true } }, events: { include: { financialAccount: { select: { name: true } } }, orderBy: { eventDate: "desc" } } }, orderBy: { createdAt: "desc" } }); return assets.map((asset) => this.values(asset)); }
  @Post() async create(@Req() request: AuthRequest, @Body() dto: CreateAssetDto) {
    if (dto.purchaseCost > 0 && !dto.financialAccountId) throw new BadRequestException("Select an account for the asset purchase"); if (Number(dto.salvageValue ?? 0) > dto.purchaseCost) throw new BadRequestException("Salvage value cannot exceed purchase cost");
    return this.prisma.$transaction(async (tx) => { let balanceAfter: number | undefined; if (dto.financialAccountId) { const account = await tx.financialAccount.findFirstOrThrow({ where: { id: dto.financialAccountId, organizationId: request.user.organizationId, active: true } }); if (Number(account.balance) < dto.purchaseCost) throw new BadRequestException("The selected account has insufficient balance"); const updatedAccount = await tx.financialAccount.update({ where: { id: account.id }, data: { balance: { decrement: dto.purchaseCost } } }); balanceAfter = Number(updatedAccount.balance); }
      const count = await tx.asset.count({ where: { organizationId: request.user.organizationId } }); const code = `AST-${String(count + 1).padStart(5, "0")}`; const purchaseDate = new Date(dto.purchaseDate); const asset = await tx.asset.create({ data: { organizationId: request.user.organizationId, code, name: dto.name, category: dto.category, description: dto.description, serialNumber: dto.serialNumber, purchaseDate, purchaseCost: dto.purchaseCost, salvageValue: dto.salvageValue ?? 0, usefulLifeMonths: dto.usefulLifeMonths, depreciationStartDate: dto.usefulLifeMonths ? purchaseDate : undefined, assignedToId: dto.assignedToId || undefined, events: { create: { type: "PURCHASE", financialAccountId: dto.financialAccountId, amount: dto.purchaseCost, eventDate: purchaseDate, description: `Purchased ${dto.name}` } } } }); if (dto.financialAccountId && balanceAfter != null) await tx.accountTransaction.create({ data: { financialAccountId: dto.financialAccountId, type: "ASSET_PURCHASE", amount: -dto.purchaseCost, balanceAfter, description: `Asset purchase: ${code} - ${dto.name}` } }); await tx.auditLog.create({ data: { organizationId: request.user.organizationId, actorId: request.user.id, action: "CREATE", entityType: "ASSET", entityId: asset.id, summary: `Added asset ${code} - ${dto.name}` } }); return asset; });
  }
  @Patch(":id") async update(@Req() request: AuthRequest, @Param("id") id: string, @Body() dto: UpdateAssetDto) { const current = await this.prisma.asset.findFirstOrThrow({ where: { id, organizationId: request.user.organizationId } }); if (current.status === "SOLD") throw new BadRequestException("A sold asset cannot be edited"); if (dto.salvageValue != null && dto.salvageValue > Number(current.purchaseCost)) throw new BadRequestException("Salvage value cannot exceed purchase cost"); const asset = await this.prisma.asset.update({ where: { id }, data: { ...dto, assignedToId: dto.assignedToId || null } }); await this.prisma.auditLog.create({ data: { organizationId: request.user.organizationId, actorId: request.user.id, action: "UPDATE", entityType: "ASSET", entityId: id, summary: `Updated asset ${asset.code}` } }); return asset; }
  @Post(":id/expenses") async expense(@Req() request: AuthRequest, @Param("id") id: string, @Body() dto: AssetExpenseDto) { return this.prisma.$transaction(async (tx) => { const asset = await tx.asset.findFirstOrThrow({ where: { id, organizationId: request.user.organizationId } }); if (asset.status === "SOLD") throw new BadRequestException("Expenses cannot be added to a sold asset"); const account = await tx.financialAccount.findFirstOrThrow({ where: { id: dto.financialAccountId, organizationId: request.user.organizationId, active: true } }); if (Number(account.balance) < dto.amount) throw new BadRequestException("The selected account has insufficient balance"); const updated = await tx.financialAccount.update({ where: { id: account.id }, data: { balance: { decrement: dto.amount } } }); const event = await tx.assetEvent.create({ data: { assetId: id, financialAccountId: account.id, type: dto.type, amount: dto.amount, eventDate: new Date(dto.eventDate), description: dto.description, reference: dto.reference } }); await tx.accountTransaction.create({ data: { financialAccountId: account.id, type: "ASSET_SERVICE", amount: -dto.amount, balanceAfter: updated.balance, description: `${dto.type}: ${asset.code} - ${asset.name}`, reference: dto.reference } }); await tx.auditLog.create({ data: { organizationId: request.user.organizationId, actorId: request.user.id, action: dto.type, entityType: "ASSET", entityId: id, summary: `${dto.type} cost LKR ${dto.amount} for ${asset.code}` } }); return event; }); }
  @Post(":id/sell") async sell(@Req() request: AuthRequest, @Param("id") id: string, @Body() dto: SellAssetDto) { return this.prisma.$transaction(async (tx) => { const asset = await tx.asset.findFirstOrThrow({ where: { id, organizationId: request.user.organizationId } }); if (asset.status === "SOLD") throw new BadRequestException("This asset is already sold"); const account = await tx.financialAccount.findFirstOrThrow({ where: { id: dto.financialAccountId, organizationId: request.user.organizationId, active: true } }); const updated = await tx.financialAccount.update({ where: { id: account.id }, data: { balance: { increment: dto.amount } } }); await tx.assetEvent.create({ data: { assetId: id, financialAccountId: account.id, type: "SALE", amount: dto.amount, eventDate: new Date(dto.soldAt), description: dto.note || `Sold ${asset.name}`, reference: dto.reference } }); await tx.accountTransaction.create({ data: { financialAccountId: account.id, type: "ASSET_SALE", amount: dto.amount, balanceAfter: updated.balance, description: `Asset sale: ${asset.code} - ${asset.name}`, reference: dto.reference } }); const sold = await tx.asset.update({ where: { id }, data: { status: "SOLD", soldAt: new Date(dto.soldAt), salePrice: dto.amount } }); await tx.auditLog.create({ data: { organizationId: request.user.organizationId, actorId: request.user.id, action: "SALE", entityType: "ASSET", entityId: id, summary: `Sold ${asset.code} for LKR ${dto.amount}` } }); return sold; }); }
}
@Module({ controllers: [AssetsController], providers: [JwtAuthGuard, RolesGuard] }) export class AssetsModule {}
