"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BadgeDollarSign, BriefcaseBusiness, Filter, FolderKanban, Search, UsersRound, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type User = { id: string; firstName: string; lastName: string; email: string; jobTitle?: string; status: string };
type Client = { id: string; name: string; status: string; _count: { projects: number } };
type TaskType = { id: string; name: string; color: string; active: boolean };
type Assignee = { user: Pick<User, "id" | "firstName" | "lastName" | "email"> };
type Task = { id: string; title: string; description?: string; status: string; priority: string; dueDate?: string; createdAt: string; laborCost?: string; revisionCount: number; taskType?: TaskType; project?: { id: string; code: string; name: string; client?: { id: string; name: string } }; assignments: Assignee[]; revisions: { revisionNumber: number; note?: string }[] };
type Project = { id: string; code: string; name: string; description?: string; status: string; priority: string; dueDate?: string; taskCostTotal: string; completionPrice?: string; client?: { id: string; name: string }; tasks: Task[]; _count: { tasks: number; invoices: number } };
type Account = { id: string; name: string; balance: string; active: boolean };
type Overview = { users: User[]; clients: Client[]; projects: Project[]; tasks: Task[]; taskTypes: TaskType[] };

const taskStatuses = ["ALL", "BACKLOG", "TODO", "IN_PROGRESS", "WAITING", "REVIEW", "REVISION", "COMPLETED", "ACCEPTED", "CANCELLED"];
const editableTaskStatuses = ["BACKLOG", "TODO", "IN_PROGRESS", "WAITING", "REVIEW", "COMPLETED", "CANCELLED"];
const projectStatuses = ["ALL", "PLANNING", "ACTIVE", "ON_HOLD", "AWAITING_CLIENT", "AT_RISK", "COMPLETED", "CANCELLED"];

export default function WorkManagementPage() {
  const [data, setData] = useState<Overview>({ users: [], clients: [], projects: [], tasks: [], taskTypes: [] }); const [accounts, setAccounts] = useState<Account[]>([]);
  const [tab, setTab] = useState<"tasks" | "projects" | "clients">("tasks"); const [search, setSearch] = useState("");
  const [status, setStatus] = useState("ALL"); const [userId, setUserId] = useState("ALL"); const [projectId, setProjectId] = useState("ALL"); const [clientId, setClientId] = useState("ALL"); const [taskTypeId,setTaskTypeId]=useState("ALL");
  const [projectTaskStatus, setProjectTaskStatus] = useState("ALL"); const [expandedProject, setExpandedProject] = useState<string>(); const [expandedClient, setExpandedClient] = useState<string>();
  const [accepting, setAccepting] = useState<Task | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const [overview, accountResponse] = await Promise.all([authFetch("/tasks/management"), authFetch("/financial-accounts")]); if (overview.ok) setData(await overview.json()); if (accountResponse.ok) setAccounts(await accountResponse.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => { const params = new URLSearchParams(window.location.search); setSearch(params.get("search") ?? ""); setUserId(params.get("userId") ?? "ALL"); void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const tasks = useMemo(() => data.tasks.filter((task) => {
    const text = `${task.title} ${task.description ?? ""} ${task.project?.name ?? ""} ${task.project?.client?.name ?? ""}`.toLowerCase();
    return (!search || text.includes(search.toLowerCase())) && (status === "ALL" || task.status === status) && (userId === "ALL" || task.assignments.some(({ user }) => user.id === userId)) && (projectId === "ALL" || task.project?.id === projectId) && (clientId === "ALL" || task.project?.client?.id === clientId) && (taskTypeId === "ALL" || (taskTypeId === "UNCATEGORIZED" ? !task.taskType : task.taskType?.id === taskTypeId));
  }), [data.tasks, search, status, userId, projectId, clientId, taskTypeId]);
  const projects = useMemo(() => data.projects.filter((project) => (!search || `${project.code} ${project.name} ${project.client?.name ?? ""}`.toLowerCase().includes(search.toLowerCase())) && (status === "ALL" || project.status === status) && (clientId === "ALL" || project.client?.id === clientId)), [data.projects, search, status, clientId]);
  async function changeTaskStatus(task: Task, nextStatus: string) { setMessage(""); const response = await authFetch(`/tasks/${task.id}/status`, { method: "PATCH", body: JSON.stringify({ status: nextStatus }) }); if (response.ok) { setMessage(nextStatus === "COMPLETED" ? "Task marked completed. Use Accept & credit to add its cost to the employee wallet." : "Task status updated."); await load(); } else { const body = await response.json(); setMessage(Array.isArray(body.message) ? body.message.join(", ") : body.message); } }
  async function accept(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!accepting) return; const form = new FormData(event.currentTarget); setSaving(true); const response = await authFetch(`/tasks/${accepting.id}/accept`, { method: "POST", body: JSON.stringify({ userId: form.get("userId"), fundingAccountId: form.get("fundingAccountId"), cost: Number(form.get("cost")) }) }); if (response.ok) { setMessage("Task accepted and the approved cost was credited to the employee wallet."); setAccepting(null); await load(); } else { const body = await response.json(); setMessage(Array.isArray(body.message) ? body.message.join(", ") : body.message); } setSaving(false); }
  function resetFilters() { setSearch(""); setStatus("ALL"); setUserId("ALL"); setProjectId("ALL"); setClientId("ALL"); setTaskTypeId("ALL"); }

  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-7xl">
    <Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link>
    <div className="mb-6"><p className="text-sm font-bold text-[#176b5b]">ADMIN CONTROL</p><h1 className="mt-1 text-3xl font-bold">Work management</h1><p className="mt-2 text-sm text-[#687570]">Review work by employee, client, or project and manage every task from one place.</p></div>
    <div className="mb-5 flex flex-wrap gap-2">{([['tasks','User-wise tasks',UsersRound],['projects','Project-wise tasks',FolderKanban],['clients','Client project history',BriefcaseBusiness]] as const).map(([value,label,Icon]) => <button key={value} onClick={() => { setTab(value); resetFilters(); }} className={`flex items-center gap-2 rounded-xl px-4 py-3 text-sm font-bold ${tab === value ? "bg-[#176b5b] text-white" : "border border-[#dce3e0] bg-white text-[#50605a]"}`}><Icon size={17}/>{label}</button>)}</div>
    <section className="card mb-5 p-4"><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-56 flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#82908a]"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks, projects or clients..." className="w-full rounded-lg border border-[#dbe2df] py-2.5 pl-9 pr-3 text-sm"/></div>{tab === "tasks" && <select value={userId} onChange={(event) => setUserId(event.target.value)} className="rounded-lg border bg-white px-3 py-2.5 text-sm"><option value="ALL">All users</option>{data.users.map((user) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select>}{tab !== "clients" && <select value={clientId} onChange={(event) => setClientId(event.target.value)} className="rounded-lg border bg-white px-3 py-2.5 text-sm"><option value="ALL">All clients</option>{data.clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select>}{tab === "tasks" && <select value={projectId} onChange={(event) => setProjectId(event.target.value)} className="rounded-lg border bg-white px-3 py-2.5 text-sm"><option value="ALL">All projects</option>{data.projects.map((project) => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select>}{tab === "tasks" && <select value={taskTypeId} onChange={(event)=>setTaskTypeId(event.target.value)} className="rounded-lg border bg-white px-3 py-2.5 text-sm"><option value="ALL">All task types</option><option value="UNCATEGORIZED">Uncategorized</option>{data.taskTypes.map(type=><option key={type.id} value={type.id}>{type.name}</option>)}</select>}{tab !== "clients" && <select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border bg-white px-3 py-2.5 text-sm">{(tab === "tasks" ? taskStatuses : projectStatuses).map((value) => <option key={value} value={value}>{value === "ALL" ? "All statuses" : value.replaceAll("_", " ")}</option>)}</select>}<button onClick={resetFilters} className="flex items-center gap-2 rounded-lg border px-3 py-2.5 text-xs font-bold"><Filter size={15}/> Reset</button></div></section>
    {message && <div className="mb-5 rounded-xl bg-[#eef7f3] p-4 text-sm font-semibold text-[#176b5b]">{message}</div>}

    {tab === "tasks" && <section className="card overflow-hidden"><div className="border-b p-5 font-bold">All task details <span className="ml-2 rounded-full bg-[#edf4f1] px-2 py-1 text-xs text-[#176b5b]">{tasks.length}</span></div><div className="divide-y">{tasks.map((task) => <article key={task.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{task.title}</h2><span className="rounded px-2 py-1 text-[10px] font-bold text-white" style={{backgroundColor:task.taskType?.color??"#7b8782"}}>{task.taskType?.name??"UNCATEGORIZED"}</span><span className="rounded bg-[#f0f3f1] px-2 py-1 text-[10px] font-bold">{task.priority}</span>{task.revisionCount > 0 && <span className="rounded bg-orange-50 px-2 py-1 text-[10px] font-bold text-orange-700">REVISION {String(task.revisionCount).padStart(2,"0")}</span>}</div><p className="mt-1 text-xs text-[#75817c]">{task.project ? `${task.project.code} · ${task.project.name}` : "General task"}{task.project?.client ? ` · ${task.project.client.name}` : ""}{task.dueDate ? ` · Due ${new Date(task.dueDate).toLocaleString()}` : ""}</p>{task.description && <p className="mt-3 text-sm text-[#52605b]">{task.description}</p>}<div className="mt-3 text-xs"><b>Assigned users:</b> {task.assignments.map(({user}) => `${user.firstName} ${user.lastName}`).join(", ") || "Unassigned"}</div>{task.revisions[0]?.note && <div className="mt-3 rounded-lg bg-orange-50 p-3 text-xs text-orange-800">Latest revision: {task.revisions[0].note}</div>}</div><div className="flex shrink-0 flex-wrap items-center gap-2"><select value={task.status} disabled={task.status === "ACCEPTED" || task.status === "REVISION"} onChange={(event) => void changeTaskStatus(task, event.target.value)} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold disabled:bg-[#edf1ef]">{editableTaskStatuses.map((value) => <option key={value}>{value}</option>)}{task.status === "ACCEPTED" && <option>ACCEPTED</option>}{task.status === "REVISION" && <option>REVISION</option>}</select>{task.status === "COMPLETED" && <button onClick={() => setAccepting(task)} className="flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white"><BadgeDollarSign size={15}/> Accept & credit</button>}{task.status === "ACCEPTED" && <span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">Rs. {Number(task.laborCost ?? 0).toLocaleString()} credited</span>}</div></div></article>)}{!tasks.length && <div className="p-10 text-center text-sm text-[#7b8782]">No tasks match these filters.</div>}</div></section>}

    {tab === "projects" && <div className="space-y-4">{projects.map((project) => { const shownTasks = project.tasks.filter((task) => projectTaskStatus === "ALL" || task.status === projectTaskStatus); return <section key={project.id} className="card overflow-hidden"><div className="flex flex-col gap-3 p-5 md:flex-row md:items-center"><div className="flex-1"><div className="text-xs font-bold text-[#176b5b]">{project.code}</div><h2 className="mt-1 font-bold">{project.name}</h2><p className="mt-1 text-xs text-[#75817c]">{project.client?.name ?? "Internal project"} · {project.status.replaceAll("_", " ")} · {project._count.tasks} tasks · {project._count.invoices} invoices</p></div><Link href={`/admin/projects/${project.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold text-[#176b5b]">Project details</Link><button onClick={() => setExpandedProject(expandedProject === project.id ? undefined : project.id)} className="rounded-lg bg-[#176b5b] px-3 py-2 text-xs font-bold text-white">{expandedProject === project.id ? "Hide tasks" : "Manage tasks"}</button></div>{expandedProject === project.id && <div className="border-t bg-[#fafcfa] p-5"><div className="mb-3 flex items-center"><b className="text-sm">Project tasks</b><select value={projectTaskStatus} onChange={(event) => setProjectTaskStatus(event.target.value)} className="ml-auto rounded-lg border bg-white px-3 py-2 text-xs">{taskStatuses.map((value) => <option key={value} value={value}>{value === "ALL" ? "All statuses" : value.replaceAll("_", " ")}</option>)}</select></div><div className="space-y-2">{shownTasks.map((task) => <div key={task.id} className="flex flex-col gap-2 rounded-lg border bg-white p-3 sm:flex-row sm:items-center"><div className="flex-1"><b className="text-sm">{task.title}</b><div className="text-xs text-[#75817c]">{task.assignments.map(({user}) => `${user.firstName} ${user.lastName}`).join(", ") || "Unassigned"}</div></div><select value={task.status} disabled={task.status === "ACCEPTED" || task.status === "REVISION"} onChange={(event) => void changeTaskStatus(task, event.target.value)} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">{editableTaskStatuses.map((value) => <option key={value}>{value}</option>)}{task.status === "ACCEPTED" && <option>ACCEPTED</option>}{task.status === "REVISION" && <option>REVISION</option>}</select>{task.status === "COMPLETED" && <button onClick={() => setAccepting(task)} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Accept & credit</button>}</div>)}{!shownTasks.length && <div className="py-5 text-center text-sm text-[#7b8782]">No matching tasks.</div>}</div></div>}</section>; })}</div>}

    {tab === "clients" && <div className="space-y-4">{data.clients.filter((client) => !search || client.name.toLowerCase().includes(search.toLowerCase())).map((client) => { const clientProjects = data.projects.filter((project) => project.client?.id === client.id); return <section key={client.id} className="card overflow-hidden"><button onClick={() => setExpandedClient(expandedClient === client.id ? undefined : client.id)} className="flex w-full items-center p-5 text-left"><div><h2 className="font-bold">{client.name}</h2><p className="mt-1 text-xs text-[#75817c]">{client.status} · {clientProjects.length} projects</p></div><span className="ml-auto text-xs font-bold text-[#176b5b]">{expandedClient === client.id ? "Hide history" : "View project history"}</span></button>{expandedClient === client.id && <div className="border-t bg-[#fafcfa] p-5"><div className="space-y-3">{clientProjects.map((project) => <div key={project.id} className="rounded-xl border bg-white p-4"><div className="flex flex-wrap items-start gap-3"><div className="flex-1"><div className="text-xs font-bold text-[#176b5b]">{project.code}</div><h3 className="font-bold">{project.name}</h3><p className="mt-1 text-xs text-[#75817c]">{project.status.replaceAll("_", " ")} · {project.tasks.length} tasks · Internal task cost Rs. {Number(project.taskCostTotal).toLocaleString()}</p></div><Link href={`/admin/projects/${project.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">Details</Link></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{project.tasks.map((task) => <div key={task.id} className="rounded-lg bg-[#f4f7f5] p-3"><div className="text-sm font-semibold">{task.title}</div><div className="mt-1 text-xs text-[#75817c]">{task.status.replaceAll("_", " ")} · {task.assignments.map(({user}) => `${user.firstName} ${user.lastName}`).join(", ") || "Unassigned"}</div></div>)}</div></div>)}{!clientProjects.length && <div className="py-6 text-center text-sm text-[#7b8782]">No project history for this client.</div>}</div></div>}</section>; })}</div>}

    {accepting && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={accept} className="w-full max-w-md rounded-2xl bg-white p-6"><div className="flex items-start"><div><p className="text-xs font-bold text-emerald-700">ACCEPT COMPLETED TASK</p><h2 className="mt-1 text-xl font-bold">{accepting.title}</h2><p className="mt-2 text-sm text-[#687570]">The approved cost will be credited once to the selected employee wallet.</p></div><button type="button" onClick={() => setAccepting(null)} className="ml-auto"><X size={20}/></button></div><div className="mt-5 space-y-3"><select required name="userId" className="w-full rounded-lg border bg-white p-3 text-sm"><option value="">Wallet recipient</option>{accepting.assignments.map(({user}) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select><select required name="fundingAccountId" className="w-full rounded-lg border bg-white p-3 text-sm"><option value="">Payment account</option>{accounts.filter((account) => account.active).map((account) => <option key={account.id} value={account.id}>{account.name} · Rs. {Number(account.balance).toLocaleString()}</option>)}</select><input required name="cost" type="number" min="0.01" step="0.01" placeholder="Approved cost (LKR)" className="w-full rounded-lg border p-3 text-sm"/><button disabled={saving || !accounts.some((account) => account.active)} className="w-full rounded-lg bg-emerald-700 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? "Crediting..." : "Accept and credit wallet"}</button></div></form></div>}
  </div></main>;
}
