"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarClock, CheckCircle2, Circle, Play, Plus, UsersRound, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type User = { id: string; firstName: string; lastName: string; jobTitle?: string };
type Client = { id: string; name: string };
type Task = { id: string; title: string; status: string; project?: { code: string; name: string; client?: Client } };
type Item = { id: string; title: string; notes?: string; status: string; client?: Client; task?: Task };
type Meeting = { id: string; title: string; scheduledAt: string; remarks?: string; specialNotes?: string; status: string; startedAt?: string; completedAt?: string; participants: { user: User }[]; items: Item[]; createdBy: User };
type Options = { users: User[]; clients: Client[]; tasks: Task[] };

const statusStyle: Record<string, string> = { SCHEDULED: "bg-blue-50 text-blue-700", IN_PROGRESS: "bg-amber-50 text-amber-700", COMPLETED: "bg-emerald-50 text-emerald-700", CANCELLED: "bg-slate-100 text-slate-600" };

export default function MeetingsPage() {
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [options, setOptions] = useState<Options>({ users: [], clients: [], tasks: [] });
  const [isAdmin, setIsAdmin] = useState(false); const [showCreate, setShowCreate] = useState(false); const [openId, setOpenId] = useState<string>();
  const [participants, setParticipants] = useState<string[]>([]); const [clientIds, setClientIds] = useState<string[]>([]); const [taskIds, setTaskIds] = useState<string[]>([]);
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async (admin: boolean) => { const responses = await Promise.all([authFetch("/meetings"), ...(admin ? [authFetch("/meetings/options")] : [])]); if (responses[0].ok) setMeetings(await responses[0].json()); if (admin && responses[1]?.ok) setOptions(await responses[1].json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); const admin = session.user.roles.includes("ADMIN"); const timer = window.setTimeout(() => { setIsAdmin(admin); void load(admin); }, 0); return () => window.clearTimeout(timer); }, [load]);
  function toggle(value: string, values: string[], setter: (next: string[]) => void) { setter(values.includes(value) ? values.filter((id) => id !== value) : [...values, value]); }
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setSaving(true); setMessage("");
    const response = await authFetch("/meetings", { method: "POST", body: JSON.stringify({ title: form.get("title"), scheduledAt: new Date(String(form.get("scheduledAt"))).toISOString(), remarks: form.get("remarks") || undefined, specialNotes: form.get("specialNotes") || undefined, participantIds: participants, clientIds, taskIds }) });
    if (response.ok) { setShowCreate(false); setParticipants([]); setClientIds([]); setTaskIds([]); formElement.reset(); await load(true); }
    else { const data = await response.json(); setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); }
    setSaving(false);
  }
  async function action(path: string, init: RequestInit = { method: "POST" }) { const response = await authFetch(path, init); if (response.ok) { const updated = await response.json() as Meeting; setMeetings((current) => current.map((meeting) => meeting.id === updated.id ? updated : meeting)); } }
  const filteredTasks = useMemo(() => { const value = search.trim().toLowerCase(); return !value ? options.tasks : options.tasks.filter((task) => `${task.title} ${task.project?.code ?? ""} ${task.project?.name ?? ""} ${task.project?.client?.name ?? ""}`.toLowerCase().includes(value)); }, [options.tasks, search]);
  const backHref = isAdmin ? "/admin" : "/employee";

  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl">
    <Link href={backHref} className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> {isAdmin ? "Command Center" : "My Work"}</Link>
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-[#176b5b]">TEAM COLLABORATION</p><h1 className="mt-1 text-3xl font-bold">Weekly meetings</h1><p className="mt-2 text-sm text-[#687570]">Plan customer and task discussions, assign attendees, and track every agenda item.</p></div>{isAdmin && <button onClick={() => { setShowCreate(true); setMessage(""); }} className="sm:ml-auto flex items-center justify-center gap-2 rounded-xl bg-[#176b5b] px-5 py-3 text-sm font-bold text-white"><Plus size={17}/> New meeting</button>}</div>
    <div className="space-y-4">{meetings.map((meeting) => { const completed = meeting.items.filter((item) => item.status === "COMPLETED").length; const expanded = openId === meeting.id; return <section key={meeting.id} className="card overflow-hidden"><button onClick={() => setOpenId(expanded ? undefined : meeting.id)} className="flex w-full flex-col gap-4 p-5 text-left md:flex-row md:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e8f2ee] text-[#176b5b]"><CalendarClock size={21}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{meeting.title}</h2><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyle[meeting.status]}`}>{meeting.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-xs text-[#697671]">{new Date(meeting.scheduledAt).toLocaleString([], { dateStyle: "full", timeStyle: "short" })}</p><div className="mt-2 flex flex-wrap gap-3 text-xs text-[#697671]"><span className="flex items-center gap-1"><UsersRound size={14}/>{meeting.participants.length} assigned</span><span>{completed}/{meeting.items.length} discussed</span></div></div><div className="h-2 w-full overflow-hidden rounded-full bg-[#e8ecea] md:w-36"><div className="h-full bg-[#176b5b]" style={{ width: `${meeting.items.length ? completed / meeting.items.length * 100 : 0}%` }}/></div></button>
      {expanded && <div className="border-t border-[#e3e9e6] p-5"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl bg-[#f7f9f8] p-4"><div className="text-xs font-bold text-[#176b5b]">REMARKS</div><p className="mt-2 whitespace-pre-wrap text-sm text-[#56635f]">{meeting.remarks || "No remarks added."}</p></div><div className="rounded-xl bg-amber-50 p-4"><div className="text-xs font-bold text-amber-800">SPECIAL THINGS</div><p className="mt-2 whitespace-pre-wrap text-sm text-amber-900">{meeting.specialNotes || "Nothing special noted."}</p></div></div><div className="mt-4 text-xs font-bold text-[#687570]">ASSIGNED USERS</div><div className="mt-2 flex flex-wrap gap-2">{meeting.participants.map(({ user }) => <span key={user.id} className="rounded-full bg-[#edf3f0] px-3 py-1.5 text-xs font-semibold">{user.firstName} {user.lastName}</span>)}</div>
        <div className="mt-6 overflow-hidden rounded-xl border border-[#dfe6e2]"><div className="bg-[#f5f8f6] px-4 py-3 text-sm font-bold">Discussion checklist</div><div className="divide-y divide-[#e4e9e6]">{meeting.items.map((item) => <div key={item.id} className="flex items-start gap-3 p-4"><button disabled={!isAdmin || meeting.status === "SCHEDULED" || meeting.status === "CANCELLED"} onClick={() => void action(`/meetings/${meeting.id}/items/${item.id}`, { method: "PATCH", body: JSON.stringify({ completed: item.status !== "COMPLETED" }) })} className="mt-0.5 disabled:cursor-not-allowed" aria-label={item.status === "COMPLETED" ? "Reopen agenda item" : "Complete agenda item"}>{item.status === "COMPLETED" ? <CheckCircle2 className="text-emerald-600" size={21}/> : <Circle className="text-[#9aa5a1]" size={21}/>}</button><div className="min-w-0 flex-1"><div className={`font-semibold ${item.status === "COMPLETED" ? "text-[#76817d] line-through" : ""}`}>{item.title}</div>{item.task?.project && <div className="mt-1 text-xs text-[#78847f]">{item.task.project.code} · {item.task.project.name}</div>}<span className={`mt-2 inline-block rounded px-2 py-1 text-[10px] font-bold ${item.status === "COMPLETED" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{item.status === "COMPLETED" ? "DISCUSSED" : "ONGOING TO TALK"}</span></div></div>)}</div></div>
        {isAdmin && <div className="mt-5 flex flex-wrap gap-3">{meeting.status === "SCHEDULED" && <button onClick={() => void action(`/meetings/${meeting.id}/start`)} className="flex items-center gap-2 rounded-lg bg-[#176b5b] px-4 py-2.5 text-sm font-bold text-white"><Play size={16}/> Start meeting</button>}{!["COMPLETED", "CANCELLED"].includes(meeting.status) && <button onClick={() => void action(`/meetings/${meeting.id}/cancel`)} className="rounded-lg border border-red-200 px-4 py-2.5 text-sm font-bold text-red-700">Cancel meeting</button>}</div>}
      </div>}
    </section>; })}{!meetings.length && <div className="card p-12 text-center"><CalendarClock className="mx-auto text-[#9aa5a1]" size={32}/><h2 className="mt-4 font-bold">No weekly meetings yet</h2><p className="mt-1 text-sm text-[#78847f]">{isAdmin ? "Create the first meeting and assign your team." : "Your assigned meetings will appear here."}</p></div>}</div>

    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><section className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white p-6"><div className="flex items-start"><div><p className="text-xs font-bold text-[#176b5b]">WEEKLY MEETING</p><h2 className="mt-1 text-xl font-bold">Create meeting</h2></div><button onClick={() => setShowCreate(false)} className="ml-auto" aria-label="Close"><X size={21}/></button></div><form onSubmit={create} className="mt-5 space-y-5"><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">MEETING TITLE<input required minLength={3} name="title" placeholder="Weekly client review" className="mt-2 w-full rounded-lg border p-3 text-sm font-normal"/></label><label className="text-xs font-bold">DATE AND TIME<input required name="scheduledAt" type="datetime-local" className="mt-2 w-full rounded-lg border p-3 text-sm font-normal"/></label></div><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">REMARKS<textarea name="remarks" placeholder="General meeting remarks" className="mt-2 min-h-24 w-full rounded-lg border p-3 text-sm font-normal"/></label><label className="text-xs font-bold">SPECIAL THINGS<textarea name="specialNotes" placeholder="Important issues, decisions, or preparation" className="mt-2 min-h-24 w-full rounded-lg border p-3 text-sm font-normal"/></label></div>
      <div><div className="text-xs font-bold">ASSIGN USERS</div><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.users.map((user) => <label key={user.id} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 text-sm ${participants.includes(user.id) ? "border-[#176b5b] bg-[#eef7f3]" : "border-[#dfe5e2]"}`}><input type="checkbox" checked={participants.includes(user.id)} onChange={() => toggle(user.id, participants, setParticipants)}/><span><b>{user.firstName} {user.lastName}</b><small className="block text-[#78847f]">{user.jobTitle || "Team member"}</small></span></label>)}</div></div>
      <div><div className="text-xs font-bold">CUSTOMERS TO DISCUSS</div><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{options.clients.map((client) => <label key={client.id} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 text-sm ${clientIds.includes(client.id) ? "border-[#176b5b] bg-[#eef7f3]" : "border-[#dfe5e2]"}`}><input type="checkbox" checked={clientIds.includes(client.id)} onChange={() => toggle(client.id, clientIds, setClientIds)}/><b>{client.name}</b></label>)}</div></div>
      <div><div className="flex items-center gap-3"><div className="text-xs font-bold">TASKS TO DISCUSS</div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search tasks, projects or clients..." className="ml-auto rounded-lg border px-3 py-2 text-xs"/></div><div className="mt-2 max-h-56 space-y-2 overflow-y-auto">{filteredTasks.map((task) => <label key={task.id} className={`flex cursor-pointer items-center gap-3 rounded-lg border p-3 text-sm ${taskIds.includes(task.id) ? "border-[#176b5b] bg-[#eef7f3]" : "border-[#dfe5e2]"}`}><input type="checkbox" checked={taskIds.includes(task.id)} onChange={() => toggle(task.id, taskIds, setTaskIds)}/><span className="min-w-0"><b>{task.title}</b><small className="block truncate text-[#78847f]">{task.project ? `${task.project.code} · ${task.project.name}` : "No project · General task"}{task.project?.client ? ` · Client: ${task.project.client.name}` : ""} · {task.status.replaceAll("_", " ")}</small></span></label>)}</div></div>
      {message && <div className="rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</div>}<button disabled={saving || (!clientIds.length && !taskIds.length)} className="w-full rounded-xl bg-[#176b5b] py-3.5 text-sm font-bold text-white disabled:opacity-50">{saving ? "Creating..." : "Create and assign meeting"}</button></form></section></div>}
  </div></main>;
}
