"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, Banknote, CreditCard, WalletCards, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Transaction = { id: string; type: string; status: string; amount: string; balanceAfter: string; description: string; reference?: string; createdAt: string; task?: { title: string; revisionCount: number }; project?: { code: string; name: string } };
type WalletUser = { id: string; firstName: string; lastName: string; email: string; jobTitle?: string; status: string; wallet: { balance: string | number; currency: string; transactions: Transaction[] } };
type FinancialAccount = { id: string; name: string; balance: string; active: boolean };

export default function AdminWalletsPage() {
  const [users, setUsers] = useState<WalletUser[]>([]); const [accounts, setAccounts] = useState<FinancialAccount[]>([]); const [payUser, setPayUser] = useState<WalletUser | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const [response, accountResponse] = await Promise.all([authFetch("/wallets"), authFetch("/financial-accounts")]); if (response.ok) setUsers(await response.json()); if (accountResponse.ok) setAccounts(await accountResponse.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function pay(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!payUser) return; const form = new FormData(event.currentTarget); setSaving(true); const response = await authFetch(`/wallets/${payUser.id}/pay`, { method: "POST", body: JSON.stringify({ amount: Number(form.get("amount")), financialAccountId: form.get("financialAccountId"), reference: form.get("reference") || undefined, note: form.get("note") || undefined }) }); if (response.ok) { setMessage(`Payment recorded for ${payUser.firstName}.`); setPayUser(null); await load(); } else { const data = await response.json(); setMessage(data.message); } setSaving(false); }
  const total = users.reduce((sum, user) => sum + Number(user.wallet.balance), 0);
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link><div className="mb-7"><p className="text-sm font-semibold text-[#176b5b]">FINANCE</p><h1 className="mt-1 text-3xl font-bold">Team wallets</h1><p className="mt-2 text-sm text-[#6d7975]">Review approved earnings and record payments to employees.</p></div>
    {message && <div className="mb-4 flex items-center justify-between rounded-xl bg-[#eef7f3] px-4 py-3 text-sm font-semibold text-[#176b5b]">{message}<button onClick={() => setMessage("")}><X size={16}/></button></div>}
    <div className="mb-5 grid gap-4 sm:grid-cols-2"><div className="card p-5"><WalletCards size={21} className="text-[#176b5b]"/><div className="mt-4 text-2xl font-bold">Rs. {total.toLocaleString()}</div><div className="text-xs text-[#7b8782]">Total payable balance</div></div><div className="card p-5"><CreditCard size={21} className="text-blue-600"/><div className="mt-4 text-2xl font-bold">{users.filter((user) => Number(user.wallet.balance) > 0).length}</div><div className="text-xs text-[#7b8782]">Employees awaiting payment</div></div></div>
    <section className="card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e5eae7] p-5 font-bold"><WalletCards size={18} className="text-[#176b5b]"/> User wallets</div><div className="divide-y divide-[#e7ebe9]">{users.map((user) => <div key={user.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e6f0ec] text-xs font-bold text-[#176b5b]">{user.firstName[0]}{user.lastName[0]}</div><div className="min-w-0 flex-1"><div className="font-semibold">{user.firstName} {user.lastName}</div><div className="text-xs text-[#7b8782]">{user.jobTitle ?? user.email}</div><div className="mt-2 text-[11px] text-[#66736e]">{user.wallet.transactions.length} recent transactions</div></div><div className="sm:text-right"><div className="text-xl font-bold">Rs. {Number(user.wallet.balance).toLocaleString()}</div><div className="text-[10px] font-bold text-[#7b8782]">AVAILABLE</div></div><button disabled={Number(user.wallet.balance) <= 0} onClick={() => setPayUser(user)} className="flex items-center justify-center gap-2 rounded-lg bg-[#176b5b] px-4 py-2.5 text-xs font-bold text-white disabled:bg-[#c9d0cd]"><Banknote size={15}/> Record payment</button></div>)}</div></section>
    <section className="card mt-5 overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e5eae7] p-5 font-bold"><CreditCard size={18} className="text-[#176b5b]"/> Recent wallet history</div><div className="divide-y divide-[#e7ebe9]">{users.flatMap((user) => user.wallet.transactions.map((transaction) => ({ user, transaction }))).sort((a, b) => new Date(b.transaction.createdAt).getTime() - new Date(a.transaction.createdAt).getTime()).map(({ user, transaction }) => <div key={transaction.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{user.firstName} {user.lastName}</div><div className="truncate text-xs text-[#6d7975]">{transaction.description}</div><div className="mt-1 text-[11px] text-[#89938f]">{new Date(transaction.createdAt).toLocaleString()}</div></div><div className={`text-sm font-bold ${Number(transaction.amount) >= 0 ? "text-emerald-700" : "text-red-600"}`}>{Number(transaction.amount) >= 0 ? "+" : "−"} Rs. {Math.abs(Number(transaction.amount)).toLocaleString()}</div><span className="w-fit rounded-full bg-[#edf4f1] px-2 py-1 text-[10px] font-bold text-[#176b5b]">{transaction.status}</span></div>)}{!users.some((user) => user.wallet.transactions.length) && <div className="p-10 text-center text-sm text-[#7b8782]">No wallet transactions yet.</div>}</div></section>
    {payUser && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-6"><div className="flex items-start"><div><p className="text-xs font-bold text-[#176b5b]">RECORD PAYMENT</p><h2 className="mt-1 text-xl font-bold">{payUser.firstName} {payUser.lastName}</h2><p className="mt-1 text-sm text-[#6d7975]">Available: Rs. {Number(payUser.wallet.balance).toLocaleString()}</p></div><button onClick={() => setPayUser(null)} className="ml-auto"><X size={20}/></button></div><form onSubmit={pay} className="mt-5 space-y-4"><label className="block text-xs font-bold">AMOUNT (LKR)<input name="amount" required type="number" min="0.01" max={Number(payUser.wallet.balance)} step="0.01" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm"/></label><label className="block text-xs font-bold">PAY FROM<select name="financialAccountId" required className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal"><option value="">Select bank or cash account</option>{accounts.filter((account) => account.active).map((account) => <option key={account.id} value={account.id}>{account.name} · Rs. {Number(account.balance).toLocaleString()}</option>)}</select></label><label className="block text-xs font-bold">PAYMENT REFERENCE<input name="reference" placeholder="Bank transfer or receipt number" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="block text-xs font-bold">NOTE<input name="note" placeholder="Salary/task payment" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><button disabled={saving || !accounts.some((account) => account.active)} className="w-full rounded-lg bg-[#176b5b] py-3 text-sm font-bold text-white disabled:bg-[#aebbb7]">{saving ? "Recording..." : "Confirm paid"}</button></form></section></div>}
  </div></main>;
}
