"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Banknote, BriefcaseBusiness, Building2, Plus, Search, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Transaction = { id: string; type: string; status: string; amount: string; balanceAfter: string; description: string; reference?: string; createdAt: string; task?: { title: string; revisionCount: number }; project?: { code: string; name: string } };
type Client = { id: string; name: string; legalName?: string; email?: string; phone?: string; industry?: string; status: string; account: { balance: string | number; currency: string; transactions: Transaction[] }; _count: { projects: number } };

export default function ClientsPage() {
  const [clients, setClients] = useState<Client[]>([]); const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false); const [payClient, setPayClient] = useState<Client | null>(null); const [editClient, setEditClient] = useState<Client | null>(null); const [expanded, setExpanded] = useState<string | null>(null);
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const response = await authFetch("/clients"); if (response.ok) setClients(await response.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return query ? clients.filter((client) => `${client.name} ${client.legalName ?? ""} ${client.email ?? ""} ${client.industry ?? ""}`.toLowerCase().includes(query)) : clients; }, [clients, search]);
  const totalDue = clients.reduce((sum, client) => sum + Number(client.account.balance), 0);

  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setSaving(true); setMessage("");
    const response = await authFetch("/clients", { method: "POST", body: JSON.stringify({ name: form.get("name"), legalName: form.get("legalName") || undefined, email: form.get("email") || undefined, phone: form.get("phone") || undefined, industry: form.get("industry") || undefined }) });
    const data = await response.json(); if (response.ok) { formElement.reset(); setShowCreate(false); setMessage("Client created successfully."); await load(); } else setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); setSaving(false);
  }
  async function pay(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!payClient) return; const form = new FormData(event.currentTarget); setSaving(true); setMessage("");
    const response = await authFetch(`/clients/${payClient.id}/payments`, { method: "POST", body: JSON.stringify({ amount: Number(form.get("amount")), reference: form.get("reference") || undefined, note: form.get("note") || undefined }) });
    const data = await response.json(); if (response.ok) { setPayClient(null); setMessage(`Payment recorded for ${payClient.name}.`); await load(); } else setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); setSaving(false);
  }
  async function update(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editClient) return; const form = new FormData(event.currentTarget); setSaving(true); setMessage("");
    const response = await authFetch(`/clients/${editClient.id}`, { method: "PATCH", body: JSON.stringify({ name: form.get("name"), legalName: form.get("legalName") || undefined, email: form.get("email") || undefined, phone: form.get("phone") || undefined, industry: form.get("industry") || undefined, status: form.get("status") }) });
    const data = await response.json(); if (response.ok) { setEditClient(null); setMessage("Client details updated."); await load(); } else setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); setSaving(false);
  }

  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl">
    <Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link>
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#176b5b]">CRM & ACCOUNTS</p><h1 className="mt-1 text-3xl font-bold">Clients</h1><p className="mt-2 text-sm text-[#6d7975]">Create clients, connect projects, track approved task charges, and record payments.</p></div><button onClick={() => setShowCreate(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#176b5b] px-5 py-3 text-sm font-bold text-white sm:ml-auto"><Plus size={17}/> Add client</button></div>
    {message && <div className="mb-4 flex items-center justify-between rounded-xl border border-[#cfe3da] bg-[#eef7f3] px-4 py-3 text-sm font-semibold text-[#176b5b]">{message}<button onClick={() => setMessage("")}><X size={16}/></button></div>}
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="card p-5"><Building2 size={20} className="text-[#176b5b]"/><div className="mt-3 text-2xl font-bold">{clients.length}</div><div className="text-xs text-[#7b8782]">Client accounts</div></div><div className="card p-5"><BriefcaseBusiness size={20} className="text-blue-600"/><div className="mt-3 text-2xl font-bold">{clients.reduce((sum, client) => sum + client._count.projects, 0)}</div><div className="text-xs text-[#7b8782]">Connected projects</div></div><div className="card p-5"><Banknote size={20} className="text-amber-600"/><div className="mt-3 text-2xl font-bold">Rs. {totalDue.toLocaleString()}</div><div className="text-xs text-[#7b8782]">Total outstanding</div></div></div>
    <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e5eae7] p-5 sm:flex-row sm:items-center"><div className="font-bold">Client accounts</div><div className="relative sm:ml-auto sm:w-72"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#87928d]"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search clients..." className="w-full rounded-lg border border-[#dbe2df] py-2.5 pl-9 pr-3 text-sm"/></div></div>
      <div className="divide-y divide-[#e7ebe9]">{visible.map((client) => <div key={client.id}><div className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#e6f0ec] font-bold text-[#176b5b]">{client.name.slice(0, 2).toUpperCase()}</div><div className="min-w-0 flex-1"><div className="font-bold">{client.name}</div><div className="text-xs text-[#7b8782]">{client.email ?? "No email"}{client.phone ? ` · ${client.phone}` : ""}{client.industry ? ` · ${client.industry}` : ""}</div><div className="mt-1 text-xs text-[#64716c]">{client._count.projects} project{client._count.projects === 1 ? "" : "s"} · {client.account.transactions.length} transactions</div></div><div className="md:text-right"><div className="text-xl font-bold">Rs. {Number(client.account.balance).toLocaleString()}</div><div className="text-[10px] font-bold text-[#7b8782]">OUTSTANDING</div></div><button onClick={() => setExpanded(expanded === client.id ? null : client.id)} className="rounded-lg border border-[#dbe2df] px-4 py-2.5 text-xs font-bold">{expanded === client.id ? "Hide history" : "View history"}</button><button disabled={Number(client.account.balance) <= 0} onClick={() => setPayClient(client)} className="flex items-center justify-center gap-2 rounded-lg bg-[#176b5b] px-4 py-2.5 text-xs font-bold text-white disabled:bg-[#c9d0cd]"><Banknote size={15}/> Record payment</button></div>
        {expanded === client.id && <div className="border-t border-[#edf0ee] bg-[#fafcfa] px-5 py-3">{client.account.transactions.map((transaction) => { const charge = Number(transaction.amount) >= 0; return <div key={transaction.id} className="flex flex-col gap-2 border-b border-[#e7ebe9] py-3 last:border-0 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{transaction.description}</div><div className="text-xs text-[#77837e]">{new Date(transaction.createdAt).toLocaleString()}{transaction.project ? ` · ${transaction.project.code}` : ""}{transaction.reference ? ` · Ref: ${transaction.reference}` : ""}</div>{transaction.task && <div className="text-xs text-[#52605b]">{transaction.task.title}{transaction.task.revisionCount ? ` · Revision ${String(transaction.task.revisionCount).padStart(2, "0")}` : ""}</div>}</div><div className={charge ? "font-bold text-red-600" : "font-bold text-emerald-700"}>{charge ? "+" : "−"} Rs. {Math.abs(Number(transaction.amount)).toLocaleString()}</div><div className="text-right text-[10px] font-bold text-[#77837e]">{transaction.status}<br/>Balance Rs. {Number(transaction.balanceAfter).toLocaleString()}</div></div>; })}{!client.account.transactions.length && <div className="py-5 text-center text-sm text-[#7b8782]">No account history yet.</div>}</div>}
      </div>)}{!visible.length && <div className="p-10 text-center text-sm text-[#7b8782]">No clients found.</div>}</div>
    </section>
    <section className="card mt-5 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div><div className="font-bold">Maintain client details</div><div className="text-xs text-[#7b8782]">Update contact details, industry, and account status.</div></div><select value={editClient?.id ?? ""} onChange={(event) => setEditClient(clients.find((client) => client.id === event.target.value) ?? null)} className="rounded-lg border border-[#dbe2df] bg-white px-3 py-2 text-sm sm:ml-auto"><option value="">Choose a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div>{editClient && <form key={editClient.id} onSubmit={update} className="mt-5 grid gap-4 border-t border-[#e7ebe9] pt-5 sm:grid-cols-3"><label className="text-xs font-bold">NAME<input name="name" required defaultValue={editClient.name} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">LEGAL NAME<input name="legalName" defaultValue={editClient.legalName} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">STATUS<select name="status" defaultValue={editClient.status} className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal">{["LEAD", "ACTIVE", "INACTIVE", "ARCHIVED"].map((status) => <option key={status}>{status}</option>)}</select></label><label className="text-xs font-bold">EMAIL<input name="email" type="email" defaultValue={editClient.email} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">PHONE<input name="phone" defaultValue={editClient.phone} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">INDUSTRY<input name="industry" defaultValue={editClient.industry} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><button disabled={saving} className="rounded-lg bg-[#176b5b] px-5 py-3 text-sm font-bold text-white sm:col-span-3">{saving ? "Saving..." : "Save client changes"}</button></form>}</section>
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-6"><div className="mb-5 flex items-center"><div><h2 className="text-xl font-bold">Create client</h2><p className="text-xs text-[#75817c]">Clients are business records and do not receive login accounts.</p></div><button onClick={() => setShowCreate(false)} className="ml-auto"><X size={20}/></button></div><form onSubmit={create} className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">DISPLAY NAME<input name="name" required minLength={2} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">LEGAL NAME<input name="legalName" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">EMAIL<input name="email" type="email" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">PHONE<input name="phone" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold sm:col-span-2">INDUSTRY<input name="industry" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border border-[#dbe2df] px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-lg bg-[#176b5b] px-5 py-2.5 text-sm font-bold text-white">{saving ? "Creating..." : "Create client"}</button></div></form></section></div>}
    {payClient && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-6"><div className="flex items-start"><div><p className="text-xs font-bold text-[#176b5b]">CLIENT PAYMENT</p><h2 className="mt-1 text-xl font-bold">{payClient.name}</h2><p className="mt-1 text-sm text-[#6d7975]">Outstanding: Rs. {Number(payClient.account.balance).toLocaleString()}</p></div><button onClick={() => setPayClient(null)} className="ml-auto"><X size={20}/></button></div><form onSubmit={pay} className="mt-5 space-y-4"><label className="block text-xs font-bold">AMOUNT (LKR)<input name="amount" required type="number" min="0.01" max={Number(payClient.account.balance)} step="0.01" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm"/></label><label className="block text-xs font-bold">PAYMENT REFERENCE<input name="reference" placeholder="Bank transfer or receipt number" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="block text-xs font-bold">NOTE<input name="note" placeholder="Payment received" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><button disabled={saving} className="w-full rounded-lg bg-[#176b5b] py-3 text-sm font-bold text-white">{saving ? "Recording..." : "Confirm payment"}</button></form></section></div>}
  </div></main>;
}
