"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, Landmark, Plus, WalletCards, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";
type Tx = { id: string; type: string; amount: string; balanceAfter: string; description: string; reference?: string; createdAt: string };
type Account = { id: string; name: string; type: string; bankName?: string; accountNumber?: string; balance: string; active: boolean; transactions: Tx[] };
export default function AccountsPage() {
 const [accounts,setAccounts]=useState<Account[]>([]); const [showCreate,setShowCreate]=useState(false); const [moveAccount,setMoveAccount]=useState<Account|null>(null); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const response=await authFetch("/financial-accounts");if(response.ok)setAccounts(await response.json());},[]);
 useEffect(()=>{const session=getSession();if(!session)return void window.location.replace("/login");if(!session.user.roles.includes("ADMIN"))return void window.location.replace("/employee");const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const el=event.currentTarget;const f=new FormData(el);setSaving(true);const response=await authFetch("/financial-accounts",{method:"POST",body:JSON.stringify({name:f.get("name"),type:f.get("type"),bankName:f.get("bankName")||undefined,accountNumber:f.get("accountNumber")||undefined,openingBalance:Number(f.get("openingBalance")||0)})});const data=await response.json();if(response.ok){setShowCreate(false);setMessage("Account created.");await load();}else setMessage(Array.isArray(data.message)?data.message.join(", "):data.message);setSaving(false);}
 async function move(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!moveAccount)return;const f=new FormData(event.currentTarget);setSaving(true);const response=await authFetch(`/financial-accounts/${moveAccount.id}/transactions`,{method:"POST",body:JSON.stringify({type:f.get("type"),amount:Number(f.get("amount")),description:f.get("description")||undefined,reference:f.get("reference")||undefined})});const data=await response.json();if(response.ok){setMoveAccount(null);setMessage("Account balance updated.");await load();}else setMessage(Array.isArray(data.message)?data.message.join(", "):data.message);setSaving(false);}
 const total=accounts.filter(a=>a.active).reduce((s,a)=>s+Number(a.balance),0);
 return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link><div className="mb-7 flex items-end"><div><p className="text-sm font-semibold text-[#176b5b]">FINANCE</p><h1 className="mt-1 text-3xl font-bold">Bank & cash accounts</h1><p className="mt-2 text-sm text-[#6d7975]">Manage company funds used for employee payments.</p></div><button onClick={()=>setShowCreate(true)} className="ml-auto flex items-center gap-2 rounded-xl bg-[#176b5b] px-5 py-3 text-sm font-bold text-white"><Plus size={17}/> Add account</button></div>{message&&<div className="mb-4 rounded-xl bg-[#eef7f3] p-4 text-sm font-semibold text-[#176b5b]">{message}</div>}<div className="card mb-5 p-6"><WalletCards className="text-[#176b5b]"/><div className="mt-3 text-3xl font-bold">Rs. {total.toLocaleString()}</div><div className="text-xs text-[#7b8782]">Total available across active accounts</div></div><div className="grid gap-5 lg:grid-cols-2">{accounts.map(account=><section key={account.id} className="card overflow-hidden"><div className="flex items-center gap-3 border-b border-[#e7ebe9] p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f2ee] text-[#176b5b]"><Landmark size={19}/></div><div><div className="font-bold">{account.name}</div><div className="text-xs text-[#7b8782]">{account.type.replaceAll("_"," ")}{account.accountNumber?` · ${account.accountNumber}`:""}</div></div><div className="ml-auto text-right"><div className="text-xl font-bold">Rs. {Number(account.balance).toLocaleString()}</div><div className="text-[10px] font-bold">{account.active?"ACTIVE":"INACTIVE"}</div></div></div><div className="max-h-56 divide-y divide-[#edf0ee] overflow-y-auto">{account.transactions.map(tx=><div key={tx.id} className="flex items-center gap-3 p-4"><div className="min-w-0 flex-1"><div className="truncate text-xs font-semibold">{tx.description}</div><div className="text-[10px] text-[#89938f]">{new Date(tx.createdAt).toLocaleString()}{tx.reference?` · ${tx.reference}`:""}</div></div><div className={`text-xs font-bold ${Number(tx.amount)>=0?"text-emerald-700":"text-red-600"}`}>{Number(tx.amount)>=0?"+":"−"} Rs. {Math.abs(Number(tx.amount)).toLocaleString()}</div></div>)}{!account.transactions.length&&<div className="p-6 text-center text-xs text-[#7b8782]">No transactions.</div>}</div><button onClick={()=>setMoveAccount(account)} className="w-full border-t border-[#e7ebe9] py-3 text-xs font-bold text-[#176b5b]">Add funds / withdraw</button></section>)}</div>
 {showCreate&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={create} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6"><div className="flex"><h2 className="text-xl font-bold">Add financial account</h2><button type="button" onClick={()=>setShowCreate(false)} className="ml-auto"><X/></button></div><input name="name" required placeholder="Sampath Bank / Cash" className="w-full rounded-lg border p-3"/><select name="type" className="w-full rounded-lg border bg-white p-3"><option>BANK</option><option>CASH</option><option>MOBILE_WALLET</option><option>OTHER</option></select><input name="bankName" placeholder="Bank name" className="w-full rounded-lg border p-3"/><input name="accountNumber" placeholder="Account number" className="w-full rounded-lg border p-3"/><input name="openingBalance" type="number" min="0" step="0.01" placeholder="Opening balance" className="w-full rounded-lg border p-3"/><button disabled={saving} className="w-full rounded-lg bg-[#176b5b] py-3 font-bold text-white">Create account</button></form></div>}
 {moveAccount&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={move} className="w-full max-w-md space-y-4 rounded-2xl bg-white p-6"><div className="flex"><div><h2 className="text-xl font-bold">Update {moveAccount.name}</h2><p className="text-sm text-[#6d7975]">Current Rs. {Number(moveAccount.balance).toLocaleString()}</p></div><button type="button" onClick={()=>setMoveAccount(null)} className="ml-auto"><X/></button></div><select name="type" className="w-full rounded-lg border bg-white p-3"><option>DEPOSIT</option><option>WITHDRAWAL</option><option>ADJUSTMENT</option></select><input name="amount" required type="number" min="0.01" step="0.01" placeholder="Amount" className="w-full rounded-lg border p-3"/><input name="description" placeholder="Description" className="w-full rounded-lg border p-3"/><input name="reference" placeholder="Reference" className="w-full rounded-lg border p-3"/><button disabled={saving} className="w-full rounded-lg bg-[#176b5b] py-3 font-bold text-white">Save transaction</button></form></div>}
 </div></main>;
}
