"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, BadgeDollarSign, CheckCircle2, ClipboardList, Plus, RotateCcw, UserPlus, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type User = { id: string; firstName: string; lastName: string; email: string; jobTitle?: string };
type Project = { id: string; name: string; code: string };
type FinancialAccount = { id: string; name: string; type: string; balance: string; active: boolean };
type Task = { id: string; title: string; priority: string; status: string; dueDate?: string; revisionCount: number; laborCost?: string; project?: Project; assignments: { user: User }[]; revisions: { revisionNumber: number; note?: string }[] };

export default function AdminTasksPage() {
  const [users, setUsers] = useState<User[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [accounts, setAccounts] = useState<FinancialAccount[]>([]);
  const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const [reviewTask, setReviewTask] = useState<Task | null>(null);
  const load = useCallback(async () => { const [u, p, t, a] = await Promise.all([authFetch("/users/assignable"), authFetch("/projects/options"), authFetch("/tasks"), authFetch("/financial-accounts")]); if (u.ok) setUsers(await u.json()); if (p.ok) setProjects(await p.json()); if (t.ok) setTasks(await t.json()); if (a.ok) setAccounts(await a.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const formElement = event.currentTarget; setSaving(true); setMessage(""); const form = new FormData(formElement);
    const body = { title: form.get("title"), description: form.get("description") || undefined, projectId: form.get("projectId") || undefined, assigneeIds: form.getAll("assigneeIds"), dueDate: form.get("dueDate") ? new Date(String(form.get("dueDate"))).toISOString() : undefined, priority: form.get("priority") };
    const response = await authFetch("/tasks", { method: "POST", body: JSON.stringify(body) });
    if (response.ok) { formElement.reset(); setMessage("Task assigned successfully."); await load(); } else { const data = await response.json(); setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); } setSaving(false);
  }
  async function requestRevision(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!reviewTask) return; const form = new FormData(event.currentTarget); setSaving(true); const response = await authFetch(`/tasks/${reviewTask.id}/revision`, { method: "POST", body: JSON.stringify({ note: form.get("note") || undefined }) }); if (response.ok) { setMessage(`Revision ${String(reviewTask.revisionCount + 1).padStart(2, "0")} requested.`); setReviewTask(null); await load(); } else { const data = await response.json(); setMessage(data.message); } setSaving(false); }
  async function acceptTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!reviewTask) return; const form = new FormData(event.currentTarget); setSaving(true); const response = await authFetch(`/tasks/${reviewTask.id}/accept`, { method: "POST", body: JSON.stringify({ userId: form.get("userId"), fundingAccountId: form.get("fundingAccountId"), cost: Number(form.get("cost")) }) }); if (response.ok) { setMessage("Task accepted, wallet credited, and payment account selected."); setReviewTask(null); await load(); } else { const data = await response.json(); setMessage(data.message); } setSaving(false); }
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl">
    <Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link>
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#176b5b]">ADMIN WORKSPACE</p><h1 className="mt-1 text-3xl font-bold">Assign and manage tasks</h1><p className="mt-2 text-sm text-[#6e7a76]">Create work, review completions, request revisions, and approve costs.</p></div><Link href="/admin/wallets" className="flex w-fit items-center gap-2 rounded-xl border border-[#176b5b] px-4 py-2.5 text-sm font-bold text-[#176b5b] sm:ml-auto"><BadgeDollarSign size={17}/> Team wallets</Link></div>
    {tasks.some((task) => task.status === "COMPLETED") && <section className="card mb-5 border-l-4 border-l-emerald-600 p-5"><div className="mb-3 flex items-center"><div><div className="font-bold">Pending acceptance</div><div className="text-xs text-[#6d7975]">Completed tasks waiting for your review and cost approval.</div></div><span className="ml-auto rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-700">{tasks.filter((task) => task.status === "COMPLETED").length}</span></div><div className="flex flex-wrap gap-2">{tasks.filter((task) => task.status === "COMPLETED").map((task) => <button key={task.id} onClick={() => setReviewTask(task)} className="rounded-lg bg-[#176b5b] px-3 py-2 text-xs font-bold text-white">Review · {task.title}</button>)}</div></section>}
    <div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]">
      <section className="card h-fit p-6"><div className="mb-5 flex items-center gap-2 font-bold"><UserPlus size={19} className="text-[#176b5b]"/> New assignment</div><form onSubmit={submit} className="space-y-4">
        <label className="block text-xs font-bold">TASK TITLE<input name="title" required minLength={3} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal outline-none focus:border-[#176b5b]" placeholder="What needs to be done?"/></label>
        <label className="block text-xs font-bold">DESCRIPTION<textarea name="description" className="mt-2 min-h-20 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal outline-none focus:border-[#176b5b]"/></label>
        <label className="block text-xs font-bold">PROJECT<select name="projectId" className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal"><option value="">General task</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.code} — {project.name}</option>)}</select></label>
        <label className="block text-xs font-bold">ASSIGN TO<select name="assigneeIds" required multiple className="mt-2 h-28 w-full rounded-lg border border-[#dbe2df] bg-white p-2 text-sm font-normal">{users.map((user) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName} — {user.jobTitle ?? user.email}</option>)}</select><span className="mt-1 block text-[10px] font-normal text-[#7b8782]">Hold Ctrl to select multiple employees.</span></label>
        <div className="grid grid-cols-2 gap-3"><label className="block text-xs font-bold">PRIORITY<select name="priority" defaultValue="MEDIUM" className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label className="block text-xs font-bold">DUE DATE<input type="datetime-local" name="dueDate" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label></div>
        {message && <div className="rounded-lg bg-[#eef7f3] p-3 text-xs font-semibold text-[#176b5b]">{message}</div>}<button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#176b5b] py-3 text-sm font-bold text-white disabled:opacity-60"><Plus size={17}/>{saving ? "Assigning..." : "Assign task"}</button>
      </form></section>
      <section className="card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e7ebe9] p-5 font-bold"><ClipboardList size={19} className="text-[#176b5b]"/> All tasks <span className="ml-auto rounded-full bg-[#edf4f1] px-2 py-1 text-xs text-[#176b5b]">{tasks.length}</span></div><div className="divide-y divide-[#e7ebe9]">{tasks.map((task) => <div key={task.id} className="p-5"><div className="flex items-start gap-3"><CheckCircle2 size={18} className={task.status === "ACCEPTED" ? "text-emerald-600" : task.status === "COMPLETED" ? "text-blue-600" : task.status === "REVISION" ? "text-orange-600" : "text-[#aab4b0]"}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{task.title}</span>{task.revisionCount > 0 && <span className="rounded-full bg-orange-50 px-2 py-0.5 text-[10px] font-bold text-orange-700">Revision {String(task.revisionCount).padStart(2, "0")}</span>}{task.status === "ACCEPTED" && <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">Accepted · Rs. {Number(task.laborCost ?? 0).toLocaleString()}</span>}</div><div className="mt-1 text-xs text-[#7b8782]">{task.project?.name ?? "General"} · {task.status.replaceAll("_", " ")} · {task.priority}</div><div className="mt-2 text-xs text-[#52605b]">Assigned: {task.assignments.map(({ user }) => `${user.firstName} ${user.lastName}`).join(", ") || "Nobody"}</div>{task.revisions[0]?.note && <div className="mt-2 rounded-lg bg-orange-50 p-2 text-xs text-orange-800">Latest revision note: {task.revisions[0].note}</div>}</div>{task.status === "COMPLETED" && <button onClick={() => setReviewTask(task)} className="ml-2 shrink-0 rounded-lg bg-[#176b5b] px-3 py-2 text-xs font-bold text-white">Review</button>}</div></div>)}{!tasks.length && <div className="p-8 text-center text-sm text-[#7b8782]">No tasks created yet.</div>}</div></section>
    </div>
    {reviewTask && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-start"><div><p className="text-xs font-bold text-[#176b5b]">COMPLETION REVIEW</p><h2 className="mt-1 text-xl font-bold">{reviewTask.title}</h2><p className="mt-1 text-xs text-[#75817c]">Choose revision or final acceptance. A task can only be credited once.</p></div><button onClick={() => setReviewTask(null)} className="ml-auto"><X size={20}/></button></div><div className="grid gap-4 md:grid-cols-2"><form onSubmit={requestRevision} className="rounded-xl border border-orange-200 bg-orange-50/50 p-4"><div className="flex items-center gap-2 font-bold text-orange-800"><RotateCcw size={17}/> Request revision {String(reviewTask.revisionCount + 1).padStart(2, "0")}</div><textarea name="note" required placeholder="Explain what must be changed..." className="mt-3 min-h-24 w-full rounded-lg border border-orange-200 bg-white p-3 text-sm"/><button disabled={saving} className="mt-3 w-full rounded-lg border border-orange-600 py-2.5 text-sm font-bold text-orange-700">Send revision</button></form><form onSubmit={acceptTask} className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"><div className="flex items-center gap-2 font-bold text-emerald-800"><BadgeDollarSign size={17}/> Accept and credit</div><select required name="userId" className="mt-3 w-full rounded-lg border border-emerald-200 bg-white p-3 text-sm"><option value="">Wallet recipient</option>{reviewTask.assignments.map(({ user }) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select><select required name="fundingAccountId" className="mt-3 w-full rounded-lg border border-emerald-200 bg-white p-3 text-sm"><option value="">Payment account</option>{accounts.filter((account) => account.active).map((account) => <option key={account.id} value={account.id}>{account.name} · Rs. {Number(account.balance).toLocaleString()}</option>)}</select><input required name="cost" type="number" min="0.01" step="0.01" placeholder="Approved cost (LKR)" className="mt-3 w-full rounded-lg border border-emerald-200 bg-white p-3 text-sm"/><button disabled={saving || !accounts.some((account) => account.active)} className="mt-3 w-full rounded-lg bg-emerald-700 py-2.5 text-sm font-bold text-white disabled:bg-[#aebbb7]">Accept final task</button>{!accounts.some((account) => account.active) && <Link href="/admin/accounts" className="mt-2 block text-center text-xs font-bold text-emerald-800">Create a payment account first</Link>}</form></div></section></div>}
  </div></main>;
}
