"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BellRing, CalendarClock, PauseCircle, PlayCircle, Plus, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";
type Project={id:string;code:string;name:string;client?:{id:string;name:string}}; type Reminder={id:string;dueDate:string;daysBefore:number;dismissed:boolean}; type Tx={id:string;amount:string;createdAt:string};
type Renewal={id:string;name:string;frequency:"MONTHLY"|"ANNUAL";amount:string;nextDueDate:string;active:boolean;notes?:string;project:Project;reminders:Reminder[];transactions:Tx[]};
const dayText=(days:number)=>days===60?"2 months":days===30?"1 month":days===14?"2 weeks":days===7?"1 week":`${days} days`;
export default function RenewalsPage(){
 const [renewals,setRenewals]=useState<Renewal[]>([]),[projects,setProjects]=useState<Project[]>([]),[show,setShow]=useState(false),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{const [r,p]=await Promise.all([authFetch("/renewals"),authFetch("/projects")]);if(r.ok)setRenewals(await r.json());if(p.ok)setProjects(await p.json());},[]); useEffect(()=>{const s=getSession();if(!s)return void window.location.replace("/login");if(!s.user.roles.includes("ADMIN"))return void window.location.replace("/employee");const t=setTimeout(()=>void load(),0);return()=>clearTimeout(t);},[load]);
 const reminders=useMemo(()=>renewals.flatMap(renewal=>renewal.reminders.map(reminder=>({renewal,reminder}))).sort((a,b)=>new Date(a.reminder.dueDate).getTime()-new Date(b.reminder.dueDate).getTime()),[renewals]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget,f=new FormData(el);setSaving(true);const r=await authFetch("/renewals",{method:"POST",body:JSON.stringify({projectId:f.get("projectId"),name:f.get("name"),frequency:f.get("frequency"),amount:Number(f.get("amount")),nextDueDate:new Date(String(f.get("nextDueDate"))).toISOString(),notes:f.get("notes")||undefined})});const d=await r.json();if(r.ok){el.reset();setShow(false);setMessage("Renewal schedule created.");await load();}else setMessage(Array.isArray(d.message)?d.message.join(", "):d.message);setSaving(false);}
 async function toggle(r:Renewal){const response=await authFetch(`/renewals/${r.id}`,{method:"PATCH",body:JSON.stringify({active:!r.active})});if(response.ok)await load();}
 async function dismiss(id:string){const response=await authFetch(`/renewals/reminders/${id}/dismiss`,{method:"POST"});if(response.ok)await load();}
 return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-6xl"><Link href="/admin" className="mb-6 flex w-fit gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link><header className="mb-7 flex items-end"><div><p className="text-sm font-semibold text-[#176b5b]">RECURRING REVENUE</p><h1 className="text-3xl font-bold">Project renewals</h1><p className="mt-2 text-sm text-[#6d7975]">Monthly and annual client charges with staged reminders.</p></div><button onClick={()=>setShow(true)} className="ml-auto flex gap-2 rounded-xl bg-[#176b5b] px-5 py-3 text-sm font-bold text-white"><Plus size={17}/> Add renewal</button></header>{message&&<div className="mb-5 rounded-xl bg-[#eef7f3] p-4 text-sm font-semibold text-[#176b5b]">{message}</div>}
 <div className="mb-5 grid gap-4 sm:grid-cols-3"><div className="card p-5"><CalendarClock className="text-[#176b5b]"/><div className="mt-3 text-2xl font-bold">{renewals.filter(r=>r.active).length}</div><div className="text-xs text-[#7b8782]">Active schedules</div></div><div className="card p-5"><BellRing className="text-orange-600"/><div className="mt-3 text-2xl font-bold">{reminders.length}</div><div className="text-xs text-[#7b8782]">Renewal reminders</div></div><div className="card p-5"><CalendarClock className="text-blue-600"/><div className="mt-3 text-2xl font-bold">Rs. {renewals.filter(r=>r.active).reduce((s,r)=>s+Number(r.amount),0).toLocaleString()}</div><div className="text-xs text-[#7b8782]">Scheduled cycle value</div></div></div>
 {reminders.length>0&&<section className="card mb-5 overflow-hidden border-l-4 border-l-orange-500"><div className="border-b p-5 font-bold text-orange-800">Upcoming renewal reminders</div><div className="divide-y">{reminders.map(({renewal,reminder})=><div key={reminder.id} className="flex flex-col gap-2 p-4 sm:flex-row sm:items-center"><BellRing size={17} className="text-orange-600"/><div className="flex-1"><b>{renewal.project.client?.name} · {renewal.name}</b><div className="text-xs text-[#7b8782]">Due {new Date(reminder.dueDate).toLocaleDateString()} · {dayText(reminder.daysBefore)} reminder</div></div><span className="font-bold">Rs. {Number(renewal.amount).toLocaleString()}</span><button onClick={()=>void dismiss(reminder.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">Dismiss</button></div>)}</div></section>}
 <section className="card overflow-hidden"><div className="border-b p-5 font-bold">Renewal schedules</div><div className="divide-y">{renewals.map(r=><div key={r.id} className={`flex flex-col gap-3 p-5 md:flex-row md:items-center ${r.active?"":"opacity-55"}`}><div className="flex-1"><div className="flex items-center gap-2"><b>{r.name}</b><span className="rounded-full bg-[#edf4f1] px-2 py-1 text-[10px] font-bold">{r.frequency}</span></div><div className="text-sm">{r.project.code} · {r.project.client?.name}</div><div className="text-xs text-[#7b8782]">Next charge {new Date(r.nextDueDate).toLocaleDateString()} · {r.transactions.length} charges recorded</div></div><div className="text-xl font-bold">Rs. {Number(r.amount).toLocaleString()}</div><button onClick={()=>void toggle(r)} className="flex items-center justify-center gap-2 rounded-lg border px-4 py-2 text-xs font-bold">{r.active?<><PauseCircle size={15}/> Pause</>:<><PlayCircle size={15}/> Resume</>}</button></div>)}{!renewals.length&&<div className="p-10 text-center text-sm">No renewal schedules yet.</div>}</div></section>
 {show&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><form onSubmit={create} className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6"><div className="flex"><div><h2 className="text-xl font-bold">Add project renewal</h2><p className="text-xs text-[#7b8782]">Only projects connected to clients are available.</p></div><button type="button" onClick={()=>setShow(false)} className="ml-auto"><X/></button></div><label className="block text-xs font-bold">PROJECT<select required name="projectId" className="mt-2 w-full rounded-lg border bg-white p-3 text-sm font-normal"><option value="">Select client project</option>{projects.filter(p=>p.client).map(p=><option key={p.id} value={p.id}>{p.code} - {p.name} ({p.client?.name})</option>)}</select></label><label className="block text-xs font-bold">RENEWAL NAME<input required name="name" placeholder="Monthly maintenance" className="mt-2 w-full rounded-lg border p-3 text-sm font-normal"/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold">FREQUENCY<select name="frequency" className="mt-2 w-full rounded-lg border bg-white p-3 text-sm font-normal"><option>MONTHLY</option><option>ANNUAL</option></select></label><label className="text-xs font-bold">AMOUNT<input required name="amount" type="number" min=".01" step=".01" className="mt-2 w-full rounded-lg border p-3 text-sm font-normal"/></label></div><label className="block text-xs font-bold">FIRST / NEXT DUE DATE<input required name="nextDueDate" type="date" className="mt-2 w-full rounded-lg border p-3 text-sm font-normal"/></label><textarea name="notes" placeholder="Notes" className="min-h-20 w-full rounded-lg border p-3"/><button disabled={saving} className="w-full rounded-lg bg-[#176b5b] py-3 font-bold text-white">Create renewal</button></form></div>}
 </div></main>;
}
