"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, KeyRound, Search, ShieldCheck, UserPlus, UsersRound, WalletCards, X } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Unit = { id: string; name: string; code: string };
type User = { id: string; firstName: string; lastName: string; email: string; jobTitle?: string; status: "ACTIVE" | "INVITED" | "SUSPENDED"; roles: { role: { name: string } }[]; businessUnits: { businessUnit: Unit }[]; _count: { assignments: number } };

export default function UsersPage() {
  const [users, setUsers] = useState<User[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [search, setSearch] = useState("");
  const [showCreate, setShowCreate] = useState(false); const [resetUser, setResetUser] = useState<User | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const [userResponse, unitResponse] = await Promise.all([authFetch("/users"), authFetch("/users/business-units")]); if (userResponse.ok) setUsers(await userResponse.json()); if (unitResponse.ok) setUnits(await unitResponse.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const visible = useMemo(() => { const query = search.toLowerCase().trim(); return query ? users.filter((user) => `${user.firstName} ${user.lastName} ${user.email} ${user.jobTitle ?? ""}`.toLowerCase().includes(query)) : users; }, [search, users]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setSaving(true); setMessage(""); const response = await authFetch("/users", { method: "POST", body: JSON.stringify({ firstName: form.get("firstName"), lastName: form.get("lastName"), email: form.get("email"), jobTitle: form.get("jobTitle") || undefined, password: form.get("password"), role: form.get("role"), businessUnitId: form.get("businessUnitId") || undefined }) }); const data = await response.json(); if (response.ok) { formElement.reset(); setShowCreate(false); setMessage("User created successfully."); await load(); } else setMessage(Array.isArray(data.message) ? data.message.join(", ") : data.message); setSaving(false); }
  async function update(id: string, changes: { status?: string; role?: string }) { const response = await authFetch(`/users/${id}/profile`, { method: "PATCH", body: JSON.stringify(changes) }); if (response.ok) { setMessage("User updated."); await load(); } else { const data = await response.json(); setMessage(data.message ?? "Update failed"); } }
  async function resetPassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!resetUser) return; const form = new FormData(event.currentTarget); setSaving(true); const response = await authFetch(`/users/${resetUser.id}/password`, { method: "PATCH", body: JSON.stringify({ password: form.get("password") }) }); if (response.ok) { setResetUser(null); setMessage(`Password reset for ${resetUser.firstName}.`); } else { const data = await response.json(); setMessage(data.message ?? "Password reset failed"); } setSaving(false); }
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-7xl">
    <Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Command Center</Link>
    <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#176b5b]">ADMINISTRATION</p><h1 className="mt-1 text-3xl font-bold">Manage users</h1><p className="mt-2 text-sm text-[#6d7975]">Create accounts, assign access, and manage your team securely.</p></div><div className="flex flex-wrap gap-2 sm:ml-auto"><Link href="/admin/wallets" className="flex w-fit items-center gap-2 rounded-xl border border-[#176b5b] bg-white px-5 py-3 text-sm font-bold text-[#176b5b]"><WalletCards size={17}/> View wallets & history</Link><button onClick={() => setShowCreate(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#176b5b] px-5 py-3 text-sm font-bold text-white"><UserPlus size={17}/> Add user</button></div></div>
    {message && <div className="mb-4 flex items-center justify-between rounded-xl border border-[#cfe3da] bg-[#eef7f3] px-4 py-3 text-sm font-semibold text-[#176b5b]">{message}<button onClick={() => setMessage("")}><X size={16}/></button></div>}
    <section className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#e5eae7] p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-2 font-bold"><UsersRound size={19} className="text-[#176b5b]"/> Team accounts <span className="rounded-full bg-[#edf4f1] px-2 py-1 text-xs text-[#176b5b]">{users.length}</span></div><div className="relative sm:ml-auto sm:w-72"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#87928d]"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search users..." className="w-full rounded-lg border border-[#dbe2df] py-2.5 pl-9 pr-3 text-sm outline-none focus:border-[#176b5b]"/></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-[#f8faf9] text-[10px] uppercase tracking-wider text-[#75817c]"><tr><th className="px-5 py-3">User</th><th className="px-4 py-3">Business unit</th><th className="px-4 py-3">Assigned tasks</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Security</th></tr></thead><tbody className="divide-y divide-[#e7ebe9]">{visible.map((user) => <tr key={user.id} className="hover:bg-[#fbfcfb]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#e5efeb] text-xs font-bold text-[#176b5b]">{user.firstName[0]}{user.lastName[0]}</div><div><div className="font-semibold">{user.firstName} {user.lastName}</div><div className="text-xs text-[#7b8782]">{user.email} · {user.jobTitle ?? "No job title"}</div></div></div></td><td className="px-4 py-4 text-sm">{user.businessUnits.map(({ businessUnit }) => businessUnit.code).join(", ")}</td><td className="px-4 py-4 text-sm font-semibold">{user._count.assignments}</td><td className="px-4 py-4"><select value={user.roles[0]?.role.name ?? "EMPLOYEE"} onChange={(event) => void update(user.id, { role: event.target.value })} className="rounded-lg border border-[#dbe2df] bg-white px-3 py-2 text-xs font-bold"><option value="EMPLOYEE">Employee</option><option value="ADMIN">Admin</option></select></td><td className="px-4 py-4"><select value={user.status} onChange={(event) => void update(user.id, { status: event.target.value })} className={`rounded-lg border px-3 py-2 text-xs font-bold ${user.status === "ACTIVE" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : user.status === "SUSPENDED" ? "border-red-200 bg-red-50 text-red-700" : "border-amber-200 bg-amber-50 text-amber-700"}`}><option value="ACTIVE">Active</option><option value="INVITED">Invited</option><option value="SUSPENDED">Suspended</option></select></td><td className="px-5 py-4 text-right"><button onClick={() => setResetUser(user)} className="inline-flex items-center gap-1.5 rounded-lg border border-[#dbe2df] px-3 py-2 text-xs font-semibold hover:border-[#176b5b] hover:text-[#176b5b]"><KeyRound size={14}/> Reset password</button></td></tr>)}</tbody></table>{!visible.length && <div className="p-10 text-center text-sm text-[#7b8782]">No users match your search.</div>}</div>
    </section>
    {showCreate && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center"><div><h2 className="text-xl font-bold">Create user account</h2><p className="mt-1 text-xs text-[#75817c]">The user can sign in immediately.</p></div><button onClick={() => setShowCreate(false)} className="ml-auto"><X size={20}/></button></div><form onSubmit={create} className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">FIRST NAME<input name="firstName" required minLength={2} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">LAST NAME<input name="lastName" required minLength={2} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold sm:col-span-2">EMAIL<input name="email" type="email" required className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">JOB TITLE<input name="jobTitle" className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><label className="text-xs font-bold">BUSINESS UNIT<select name="businessUnitId" className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal">{units.map((unit) => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label className="text-xs font-bold">ROLE<select name="role" defaultValue="EMPLOYEE" className="mt-2 w-full rounded-lg border border-[#dbe2df] bg-white p-3 text-sm font-normal"><option value="EMPLOYEE">Employee</option><option value="ADMIN">Admin</option></select></label><label className="text-xs font-bold">TEMPORARY PASSWORD<input name="password" type="password" required minLength={8} className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><div className="flex justify-end gap-3 sm:col-span-2"><button type="button" onClick={() => setShowCreate(false)} className="rounded-lg border border-[#dbe2df] px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="flex items-center gap-2 rounded-lg bg-[#176b5b] px-5 py-2.5 text-sm font-bold text-white"><UserPlus size={16}/>{saving ? "Creating..." : "Create user"}</button></div></form></section></div>}
    {resetUser && <div className="fixed inset-0 z-50 grid place-items-center bg-black/40 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-start"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f2ee] text-[#176b5b]"><ShieldCheck size={20}/></div><div className="ml-3"><h2 className="font-bold">Reset password</h2><p className="text-xs text-[#75817c]">{resetUser.firstName} {resetUser.lastName}</p></div><button onClick={() => setResetUser(null)} className="ml-auto"><X size={20}/></button></div><form onSubmit={resetPassword}><label className="text-xs font-bold">NEW TEMPORARY PASSWORD<input name="password" type="password" minLength={8} required className="mt-2 w-full rounded-lg border border-[#dbe2df] p-3 text-sm font-normal"/></label><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setResetUser(null)} className="rounded-lg border border-[#dbe2df] px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-lg bg-[#176b5b] px-5 py-2.5 text-sm font-bold text-white">Reset password</button></div></form></section></div>}
  </div></main>;
}
