"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, BarChart3, Download, Printer, RefreshCw } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Row = Record<string, unknown>;
type Report = { range: { from: string; to: string; generatedAt: string }; summary: Record<string, number>; tasks: Row[]; projects: Row[]; clients: Row[]; employees: Row[]; invoices: Row[]; payments: { received: Row[]; paid: Row[] }; clientTransactions: Row[] };
const tabs = ["tasks", "projects", "clients", "employees", "invoices", "payments"] as const;
type Tab = typeof tabs[number];
const money = (value: unknown) => `Rs. ${Number(value ?? 0).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
const label = (value: string) => value.replaceAll(/([A-Z])/g, " $1").replaceAll("_", " ").trim().replace(/^./, (char) => char.toUpperCase());
const printable = (value: unknown) => value instanceof Date ? value.toLocaleDateString() : value == null || value === "" ? "—" : typeof value === "string" && /^\d{4}-\d{2}-\d{2}T/.test(value) ? new Date(value).toLocaleDateString() : String(value);

export default function ReportsPage() {
  const today = new Date(); const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);
  const [from, setFrom] = useState(monthStart.toLocaleDateString("en-CA")); const [to, setTo] = useState(today.toLocaleDateString("en-CA")); const [report, setReport] = useState<Report | null>(null); const [tab, setTab] = useState<Tab>("tasks"); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (start: string, end: string) => { setLoading(true); setError(""); const response = await authFetch(`/reports?from=${start}&to=${end}`); const data = await response.json(); if (response.ok) setReport(data); else setError(Array.isArray(data.message) ? data.message.join(", ") : data.message); setLoading(false); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); if (!session.user.roles.includes("ADMIN")) return void window.location.replace("/employee"); const timer = window.setTimeout(() => void load(from, to), 0); return () => window.clearTimeout(timer); }, [from, load, to]);
  const rows = useMemo<Row[]>(() => { if (!report) return []; if (tab === "payments") return [...report.payments.received.map((row) => ({ direction: "Received", ...row })), ...report.payments.paid.map((row) => ({ direction: "Paid", ...row }))]; return report[tab] as Row[]; }, [report, tab]);
  const columns = useMemo(() => { const preferred: Record<Tab, string[]> = { tasks: ["title", "project", "client", "assignees", "status", "priority", "dueDate", "cost"], projects: ["code", "name", "client", "status", "tasks", "budget", "taskCost", "dueDate"], clients: ["name", "status", "projects", "outstanding", "email", "phone"], employees: ["name", "status", "assigned", "completed", "earned", "wallet"], invoices: ["invoiceNumber", "client", "project", "status", "issueDate", "dueDate", "total", "paid", "due"], payments: ["direction", "date", "party", "description", "account", "method", "reference", "amount"] }; return preferred[tab]; }, [tab]);
  function preset(days: number) { const end = new Date(); const start = new Date(); start.setDate(end.getDate() - days + 1); setFrom(start.toLocaleDateString("en-CA")); setTo(end.toLocaleDateString("en-CA")); }
  function exportCsv() { const escape = (value: unknown) => `"${printable(value).replaceAll('"', '""')}"`; const csv = [columns.map(label).map(escape).join(","), ...rows.map((row) => columns.map((column) => escape(row[column])).join(","))].join("\r\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `aurilink-${tab}-${from}-to-${to}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  const isMoney = (column: string) => ["cost", "budget", "taskCost", "outstanding", "earned", "wallet", "total", "paid", "due", "amount"].includes(column);
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8 print:bg-white print:p-0"><div className="mx-auto max-w-[1400px]"><Link href="/admin" className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#176b5b] print:hidden"><ArrowLeft size={16}/> Command Center</Link><div className="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end"><div><p className="text-sm font-semibold text-[#176b5b]">BUSINESS INTELLIGENCE</p><h1 className="mt-1 text-3xl font-bold">Reports</h1><p className="mt-2 text-sm text-[#6d7975]">Operational and financial performance for a selected period.</p></div><div className="flex flex-wrap items-end gap-2 lg:ml-auto print:hidden"><label className="text-[10px] font-bold">FROM<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="mt-1 block rounded-lg border border-[#dbe2df] bg-white px-3 py-2 text-sm font-normal"/></label><label className="text-[10px] font-bold">TO<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="mt-1 block rounded-lg border border-[#dbe2df] bg-white px-3 py-2 text-sm font-normal"/></label><button onClick={() => preset(7)} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">7 days</button><button onClick={() => preset(30)} className="rounded-lg border bg-white px-3 py-2 text-xs font-bold">30 days</button><button onClick={() => void load(from, to)} className="grid h-9 w-9 place-items-center rounded-lg bg-[#176b5b] text-white"><RefreshCw size={16}/></button><button onClick={exportCsv} disabled={!rows.length} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><Download size={15}/> CSV</button><button onClick={() => window.print()} className="flex items-center gap-2 rounded-lg border bg-white px-3 py-2 text-xs font-bold"><Printer size={15}/> Print</button></div></div>
    {error && <div className="mb-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{loading && <div className="mb-5 rounded-xl bg-white p-4 text-sm">Generating report...</div>}
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Revenue received", report?.summary.revenue, "text-emerald-700"], ["Labor cost", report?.summary.laborCost, "text-orange-700"], ["Gross profit", report?.summary.grossProfit, Number(report?.summary.grossProfit) >= 0 ? "text-emerald-700" : "text-red-600"], ["Invoice due", report?.summary.invoiceDue, "text-red-600"]].map(([title, value, color]) => <div key={String(title)} className="card p-5"><BarChart3 size={18} className={String(color)}/><div className={`mt-3 text-2xl font-bold ${color}`}>{money(value)}</div><div className="text-xs text-[#7b8782]">{String(title)}</div></div>)}</div>
    <div className="mb-5 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{[["Tasks",report?.summary.tasks],["Completed",report?.summary.completedTasks],["Projects",report?.summary.projects],["Customers",report?.summary.clients],["Employees",report?.summary.employees],["Pending accept",report?.summary.pendingAcceptance]].map(([title,value])=><div key={String(title)} className="card p-4"><div className="text-xl font-bold">{Number(value??0).toLocaleString()}</div><div className="text-[11px] text-[#7b8782]">{String(title)}</div></div>)}</div>
    <section className="card overflow-hidden"><div className="flex flex-wrap gap-2 border-b border-[#e5eae7] p-4 print:hidden">{tabs.map((value) => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-3 py-2 text-xs font-bold ${tab === value ? "bg-[#176b5b] text-white" : "bg-[#eef2f0] text-[#596661]"}`}>{label(value)}</button>)}</div><div className="hidden border-b p-4 text-sm print:block"><strong>{label(tab)} report</strong> · {new Date(from).toLocaleDateString()} to {new Date(to).toLocaleDateString()}</div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#f8faf9] uppercase tracking-wider text-[#75817c]"><tr>{columns.map((column) => <th key={column} className="px-4 py-3">{label(column)}</th>)}</tr></thead><tbody className="divide-y divide-[#e7ebe9]">{rows.map((row, index) => <tr key={String(row.id ?? index)} className="hover:bg-[#fbfcfb]">{columns.map((column) => <td key={column} className="max-w-64 px-4 py-3">{isMoney(column) ? money(row[column]) : printable(row[column])}</td>)}</tr>)}</tbody></table>{!rows.length && <div className="p-10 text-center text-sm text-[#7b8782]">No {tab} data in this date range.</div>}</div></section><div className="mt-3 text-right text-[10px] text-[#89938f]">Generated {report ? new Date(report.range.generatedAt).toLocaleString() : "—"}</div>
  </div></main>;
}
