"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, Check, ListTodo, Plus, Trash2 } from "lucide-react";
import { authFetch, getSession } from "@/lib/auth";

type Todo = { id: string; title: string; notes?: string; dueDate?: string; completed: boolean };

export default function TodoPage() {
  const [todos, setTodos] = useState<Todo[]>([]); const [isAdmin, setIsAdmin] = useState(false); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const response = await authFetch("/todos"); if (response.ok) setTodos(await response.json()); }, []);
  useEffect(() => { const session = getSession(); if (!session) return void window.location.replace("/login"); const timer = window.setTimeout(() => { setIsAdmin(session.user.roles.includes("ADMIN")); void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); setSaving(true); const response = await authFetch("/todos", { method: "POST", body: JSON.stringify({ title: form.get("title"), notes: form.get("notes") || undefined, dueDate: form.get("dueDate") ? new Date(String(form.get("dueDate"))).toISOString() : undefined }) }); if (response.ok) { formElement.reset(); await load(); } setSaving(false); }
  async function toggle(todo: Todo) { const response = await authFetch(`/todos/${todo.id}`, { method: "PATCH", body: JSON.stringify({ completed: !todo.completed }) }); if (response.ok) await load(); }
  async function remove(id: string) { const response = await authFetch(`/todos/${id}`, { method: "DELETE" }); if (response.ok) await load(); }
  return <main className="min-h-screen bg-[#f3f6f4] p-5 md:p-8"><div className="mx-auto max-w-4xl"><div className="mb-6 flex items-center"><Link href={isAdmin ? "/admin" : "/employee"} className="flex items-center gap-2 text-sm font-semibold text-[#176b5b]"><ArrowLeft size={16}/> Back to dashboard</Link><Link href="/calendar" className="ml-auto flex items-center gap-2 rounded-lg border border-[#d9e1dd] bg-white px-3 py-2 text-sm font-semibold"><CalendarDays size={16}/> Calendar</Link></div>
    <div className="mb-7"><p className="text-sm font-semibold text-[#176b5b]">PRIVATE WORKSPACE</p><h1 className="mt-1 text-3xl font-bold">My personal to-do list</h1><p className="mt-2 text-sm text-[#6d7975]">Only you can see these items. They are separate from tasks assigned by administrators.</p></div>
    <section className="card mb-5 p-5"><form onSubmit={add} className="grid gap-3 md:grid-cols-[1fr_190px_auto]"><input name="title" required placeholder="Add a personal reminder..." className="rounded-lg border border-[#d9e1dd] px-3 py-2.5 text-sm outline-none focus:border-[#176b5b]"/><input name="dueDate" type="datetime-local" className="rounded-lg border border-[#d9e1dd] px-3 py-2.5 text-sm"/><button disabled={saving} className="flex items-center justify-center gap-2 rounded-lg bg-[#176b5b] px-5 py-2.5 text-sm font-bold text-white"><Plus size={16}/>{saving ? "Adding..." : "Add"}</button><textarea name="notes" placeholder="Optional notes" className="min-h-16 rounded-lg border border-[#d9e1dd] p-3 text-sm md:col-span-3"/></form></section>
    <section className="card overflow-hidden"><div className="flex items-center gap-2 border-b border-[#e5eae7] p-5 font-bold"><ListTodo size={19} className="text-[#176b5b]"/> My items <span className="ml-auto rounded-full bg-[#edf4f1] px-2 py-1 text-xs text-[#176b5b]">{todos.filter((todo) => !todo.completed).length} open</span></div><div className="divide-y divide-[#e7ebe9]">{todos.map((todo) => <div key={todo.id} className={`flex items-start gap-3 p-4 ${todo.completed ? "bg-[#fafbfa] opacity-60" : ""}`}><button onClick={() => void toggle(todo)} className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded border ${todo.completed ? "border-[#176b5b] bg-[#176b5b] text-white" : "border-[#aeb9b4]"}`}>{todo.completed && <Check size={13}/>}</button><div className="min-w-0 flex-1"><div className={`font-semibold ${todo.completed ? "line-through" : ""}`}>{todo.title}</div>{todo.notes && <p className="mt-1 text-xs text-[#72807a]">{todo.notes}</p>}{todo.dueDate && <p className="mt-2 flex items-center gap-1.5 text-[11px] text-[#7c8883]"><CalendarDays size={13}/>{new Date(todo.dueDate).toLocaleString()}</p>}</div><button onClick={() => void remove(todo.id)} className="text-[#9aa49f] hover:text-red-600" title="Delete"><Trash2 size={17}/></button></div>)}{!todos.length && <div className="p-10 text-center text-sm text-[#7c8883]">Your personal list is empty.</div>}</div></section>
  </div></main>;
}
